export type CategoryId = 'food' | 'sights' | 'culture' | 'shopping' | 'daytrip';

export type GuideItem = {
  id: string;
  category: CategoryId;
  name: string;
  englishName: string;
  area: string;
  eyebrow: string;
  summary: string;
  description: string;
  image: string;
  imageAlt: string;
  imageCredit: string;
  duration: string;
  budget: string;
  bestTime: string;
  reservation: string;
  essentials: string[];
  highlights: { title: string; text: string }[];
  transit: string;
  routeTip: string;
  tips: string[];
  tags: string[];
  coordinates: { lat: number; lng: number };
  address: string;
  officialUrl: string;
};

export const categoryMeta = {
  food: { label: '맛집', shortLabel: '먹다', kicker: 'EAT', lead: '뉴욕의 시간을 맛보는 테이블', essentialsLabel: '대표 메뉴' },
  sights: { label: '볼거리', shortLabel: '보다', kicker: 'SEE', lead: '맨해튼의 스케일을 가장 잘 느끼는 장면', essentialsLabel: '놓치지 말 것' },
  culture: { label: '문화', shortLabel: '즐기다', kicker: 'FEEL', lead: '공연과 예술로 읽는 뉴욕', essentialsLabel: '핵심 경험' },
  shopping: { label: '쇼핑', shortLabel: '고르다', kicker: 'SHOP', lead: '뉴욕에서만 고를 수 있는 물건과 거리', essentialsLabel: '사야 할 것' },
  daytrip: { label: '근교 여행지', shortLabel: '떠나다', kicker: 'ESCAPE', lead: '도시에서 잠시 빠져나가는 하루', essentialsLabel: '하루의 핵심' },
} satisfies Record<CategoryId, { label: string; shortLabel: string; kicker: string; lead: string; essentialsLabel: string }>;

export const guideItems: GuideItem[] = [
  // FOOD · 12
  {
    id: 'katzs-deli', category: 'food', name: '카츠 델리카트슨', englishName: "Katz's Delicatessen", area: '로어 이스트 사이드 · 맨해튼',
    eyebrow: '1888년부터 이어진 뉴욕식 델리', summary: '손으로 썬 두툼한 파스트라미와 북적이는 카운터가 함께 만드는 전형적인 뉴욕 한 끼.',
    description: '입장 때 받은 티켓에 주문 금액을 표시하고 퇴장 때 정산하는 오래된 방식을 쓴다. 샌드위치 하나가 매우 커서 두 사람이 사이드와 함께 나누면 알맞다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Katz%E2%80%99s_Delicatessen_%282024%29-L1005652.jpg/1920px-Katz%E2%80%99s_Delicatessen_%282024%29-L1005652.jpg', imageAlt: '카츠 델리카트슨의 네온 간판과 외관', imageCredit: 'Wikimedia Commons · Frank Schulenburg · CC BY-SA 4.0',
    duration: '45분–1시간 15분', budget: '$$', bestTime: '평일 11:00 이전 또는 15:00–17:00', reservation: '예약 불필요 · 입장 티켓 분실 주의',
    essentials: ['파스트라미 온 라이', '포테이토 라트케', '마초볼 수프'],
    highlights: [{ title: '대표 주문', text: '파스트라미 샌드위치 하나와 피클, 라트케를 둘이 나누면 양과 맛의 균형이 좋다.' }, { title: '주문 방식', text: '커터 줄에서 고기를 고르고 작은 시식 후 주문한다. 팁을 줄 경우 카운터에서 바로 건넨다.' }],
    transit: 'F선 2 Av역에서 도보 약 4분, F·M·J·Z선 Delancey St–Essex St역에서 약 7분.', routeTip: '테너먼트 뮤지엄 → 카츠 → 이스트강 산책 순서로 로어 이스트 사이드 반나절을 만든다.',
    tips: ['입장 티켓은 주문하지 않아도 퇴장 때 필요하다.', '피크 시간에는 테이블 담당 주문보다 셀프 카운터가 빠르다.'], tags: ['파스트라미', '뉴욕 클래식', '나눠 먹기'],
    coordinates: { lat: 40.7223431, lng: -73.987353 }, address: '205 E Houston St, New York, NY 10002', officialUrl: 'https://katzsdelicatessen.com/',
  },
  {
    id: 'russ-daughters-cafe', category: 'food', name: '러스 앤 도터스 카페', englishName: 'Russ & Daughters Cafe', area: '로어 이스트 사이드 · 맨해튼',
    eyebrow: '훈제 연어와 베이글의 4대째 이야기', summary: '노바 연어, 크림치즈, 라트케를 앉아서 천천히 즐기는 뉴욕 유대계 식문화의 정수.',
    description: '1914년 식료품점에서 출발한 브랜드의 풀서비스 카페다. 원조점보다 좌석과 따뜻한 요리가 많아 둘이 여유롭게 아침이나 점심을 먹기 좋다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/NYC_-_Russ_%26_Daughters_Cafe_%28Oct_2015%29_-_05.jpg/1920px-NYC_-_Russ_%26_Daughters_Cafe_%28Oct_2015%29_-_05.jpg', imageAlt: '러스 앤 도터스 카페의 밝은 실내', imageCredit: 'Wikimedia Commons · City Foodsters · CC BY 2.0',
    duration: '1시간–1시간 30분', budget: '$$', bestTime: '오픈 직후', reservation: '워크인 운영 · 2026년 9월 21일 욤키푸르 휴무',
    essentials: ['가스페 노바 연어 플래터', '감자 라트케', '에그 크림'],
    highlights: [{ title: '둘이 먹기', text: '노바 연어 플래터에 베이글을 추가하고 라트케 하나를 곁들이면 여러 맛을 무리 없이 경험한다.' }, { title: '영업 리듬', text: '마지막 착석은 월–목 14:30, 금–일 15:30 전후라 늦은 점심은 피하는 편이 안전하다.' }],
    transit: 'F선 2 Av역 또는 F·M·J·Z선 Delancey St–Essex St역에서 도보 약 7분.', routeTip: '뉴 뮤지엄·놀리타를 본 뒤 카페, 테너먼트 뮤지엄 순서로 이동하면 되돌아감이 적다.',
    tips: ['원조 테이크아웃점과 카페 주소가 다르다.', '연어 종류와 염도가 다르니 서버에게 가장 부드러운 조합을 물어본다.'], tags: ['베이글', '훈제 연어', '브런치'],
    coordinates: { lat: 40.7196388, lng: -73.9895629 }, address: '127 Orchard St, New York, NY 10002', officialUrl: 'https://shop.russanddaughters.com/locations',
  },
  {
    id: 'joes-pizza-carmine', category: 'food', name: '조스 피자 카민 스트리트', englishName: "Joe's Pizza", area: '그리니치 빌리지 · 맨해튼',
    eyebrow: '접어 먹는 뉴욕 슬라이스의 기준', summary: '얇고 바삭한 도우, 산뜻한 토마토소스, 치즈의 균형이 정확한 빠른 한 조각.',
    description: '1975년 문을 연 원조점으로 좌석은 적고 회전이 빠르다. 화려한 토핑보다 플레인과 페퍼로니를 한 장씩 비교하면 뉴욕식 피자의 장점이 선명하다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Joe%27s_Pizza%2C_Greenwich_Village%2C_NYC.jpg/1920px-Joe%27s_Pizza%2C_Greenwich_Village%2C_NYC.jpg', imageAlt: '그리니치 빌리지 조스 피자 원조점', imageCredit: 'Wikimedia Commons · Steam Pipe Trunk Distribution Venue · CC BY 2.0',
    duration: '20–40분', budget: '$', bestTime: '14:00–17:00', reservation: '예약 불필요',
    essentials: ['플레인 치즈 슬라이스', '페퍼로니 슬라이스', '탄산음료'],
    highlights: [{ title: '먹는 법', text: '갓 데운 슬라이스를 세로로 가볍게 접으면 끝까지 바삭하게 먹기 좋다.' }, { title: '분위기', text: '서서 먹거나 짧게 머무는 곳이다. 긴 식사보다 산책 중 간식으로 잡아야 만족도가 높다.' }],
    transit: 'A·C·E·B·D·F·M선 W 4 St–Washington Sq역에서 도보 약 3분.', routeTip: '워싱턴 스퀘어 → 조스 피자 → 크리스토퍼 스트리트와 허드슨강 일몰로 잇는다.',
    tips: ['원조점은 7 Carmine St인지 주소를 확인한다.', '현금과 카드 모두 준비하면 줄에서 결제가 빠르다.'], tags: ['피자', '가성비', '간식'],
    coordinates: { lat: 40.7305467, lng: -74.0020629 }, address: '7 Carmine St, New York, NY 10014', officialUrl: 'https://www.joespizzanyc.com/',
  },
  {
    id: 'los-tacos-chelsea', category: 'food', name: '로스 타코스 넘버원', englishName: 'Los Tacos No. 1 · Chelsea Market', area: '첼시 · 맨해튼',
    eyebrow: '서해안 감성으로 만든 시장 속 타케리아', summary: '직화 고기와 갓 구운 또르띠야가 중심인, 첼시마켓에서 가장 빠르고 만족도 높은 한 끼.',
    description: '티후아나 출신 창업자들이 시작한 스탠딩 타코 가게다. 아사다와 아도바다를 옥수수 또르띠야로 한 개씩 주문하면 서로 다른 불향을 비교하기 좋다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Chelsea_Market_in_2015.JPG/1920px-Chelsea_Market_in_2015.JPG', imageAlt: '로스 타코스가 있는 첼시마켓 내부', imageCredit: 'Wikimedia Commons · MusikAnimal · CC BY-SA 4.0',
    duration: '30–50분', budget: '$', bestTime: '평일 11:00 또는 15:00', reservation: '예약 불필요 · 피크 시간 줄 있음',
    essentials: ['카르네 아사다 타코', '아도바다 타코', '선인장 노팔 타코'],
    highlights: [{ title: '주문 포인트', text: '메뉴판에 작게 표시된 퀘사타코는 치즈 풍미가 강하다. 기본 타코와 하나씩 섞는 편이 좋다.' }, { title: '시장 활용', text: '한 곳에서 배를 채우기보다 타코 2개 뒤 다른 매장의 디저트를 나누면 첼시마켓을 폭넓게 즐긴다.' }],
    transit: 'A·C·E·L선 14 St–8 Av역에서 도보 약 5분. 첼시마켓 1층.', routeTip: '첼시마켓 → 하이라인 남단 → 리틀 아일랜드 순서로 평지 위주 3시간 코스를 만든다.',
    tips: ['좌석보다 스탠딩 테이블 중심이다.', '살사는 매울 수 있으니 처음에는 적게 올린다.'], tags: ['타코', '첼시마켓', '빠른 식사'],
    coordinates: { lat: 40.7420513, lng: -74.0048973 }, address: '75 9th Ave, New York, NY 10011', officialUrl: 'https://www.lostacos1.com/location/los-tacos-chelsea-market/',
  },
  {
    id: 'xian-famous-foods', category: 'food', name: '시안 페이머스 푸즈', englishName: "Xi'an Famous Foods · Chinatown", area: '차이나타운 · 맨해튼',
    eyebrow: '손으로 뽑은 면과 큐민 향의 뉴욕 이민자 음식', summary: '쫄깃한 비앙비앙면과 매콤한 양고기로 만나는 서북 중국과 뉴욕의 교차점.',
    description: '플러싱의 작은 푸드코트에서 시작해 뉴욕을 대표하는 로컬 체인이 됐다. 넓고 납작한 면은 시간이 지나면 불기 쉬워 포장보다 매장에서 바로 먹는 편이 좋다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Xi%27an_Famous_Foods_Feast.jpg', imageAlt: '시안 페이머스 푸즈의 면과 양고기 요리', imageCredit: 'Wikimedia Commons · Ilikefood · CC BY-SA 4.0',
    duration: '35–60분', budget: '$', bestTime: '11:00–12:00 또는 15:00', reservation: '예약 불필요',
    essentials: ['N1 매운 큐민 양고기 면', '매운 새콤 시금치 만두', '큐민 양고기 버거'],
    highlights: [{ title: '맵기 조절', text: '기본도 향신료와 고추기름이 강하다. 처음이면 맵기 한 단계 낮추고 식초 풍미를 살린다.' }, { title: '기념품', text: '공식 칠리오일과 요리책은 집에서 뉴욕의 맛을 재현하기 좋은 실용적인 선물이다.' }],
    transit: '6·N·Q·R·W·J·Z선 Canal St역에서 도보 약 6분.', routeTip: '콜럼버스 파크 → 차이나타운 골목 → 시안 → 맨해튼 브리지 입구까지 짧게 걷는다.',
    tips: ['면은 주문 즉시 먹는 것이 핵심이다.', '양이 넉넉하므로 면 하나와 만두를 둘이 나눠도 충분하다.'], tags: ['누들', '매운맛', '차이나타운'],
    coordinates: { lat: 40.715052, lng: -73.9973654 }, address: '45 Bayard St, New York, NY 10013', officialUrl: 'https://www.xianfoods.com/locations',
  },
  {
    id: 'keens-steakhouse', category: 'food', name: '킨스 스테이크하우스', englishName: 'Keens Steakhouse', area: '헤럴드 스퀘어 · 맨해튼',
    eyebrow: '1885년부터 이어진 뉴욕의 다이닝 룸', summary: '파이프가 빼곡한 천장 아래에서 포터하우스와 머튼촙을 맛보는 클래식 뉴욕.',
    description: '브로드웨이 배우와 출판인이 드나들던 19세기 클럽의 분위기가 남은 스테이크하우스다. 둘이라면 메인 하나와 사이드 두 가지를 나누는 구성이 부담이 적다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Keens_Steakhouse_%2854821833498%29.jpg/1920px-Keens_Steakhouse_%2854821833498%29.jpg', imageAlt: '킨스 스테이크하우스의 역사적인 외관', imageCredit: 'Wikimedia Commons · Kidfly182 · CC BY-SA 4.0',
    duration: '1시간 30분–2시간', budget: '$$$$', bestTime: '평일 17:00–18:00', reservation: '저녁 예약 권장',
    essentials: ['프라임 포터하우스', '레전더리 머튼촙', '크림드 스피니치'],
    highlights: [{ title: '공간', text: '천장을 덮은 오래된 클레이 파이프와 짙은 목재 인테리어가 박물관 같은 분위기를 만든다.' }, { title: '두 사람 주문법', text: '포터하우스 또는 머튼촙 하나를 중심으로 사이드를 나누고 올드패션드 한 잔을 더한다.' }],
    transit: 'B·D·F·M·N·Q·R·W선 34 St–Herald Sq역에서 도보 약 3분.', routeTip: '엠파이어 스테이트 빌딩 또는 모건 라이브러리 관람 뒤 이른 저녁으로 연결한다.',
    tips: ['복장은 스마트 캐주얼이면 충분하다.', '머튼촙은 양이 크고 향이 뚜렷해 취향을 확인한다.'], tags: ['스테이크', '역사', '기념일'],
    coordinates: { lat: 40.7506, lng: -73.9864 }, address: '72 W 36th St, New York, NY 10018', officialUrl: 'https://www.keens.com/',
  },
  {
    id: 'gramercy-tavern', category: 'food', name: '그래머시 태번', englishName: 'Gramercy Tavern', area: '플랫아이언 · 맨해튼',
    eyebrow: '계절을 담는 현대적 뉴욕 아메리칸', summary: '따뜻한 목재 공간에서 정교한 코스와 편안한 태번 요리를 선택할 수 있는 기념일 레스토랑.',
    description: '한 공간 안에 예약 중심 다이닝룸과 비교적 캐주얼한 태번이 나뉜다. 긴 코스가 부담되면 태번에서 제철 애피타이저와 장작불 메인을 나누는 방식이 좋다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Gramercy_Tavern.jpg/1920px-Gramercy_Tavern.jpg', imageAlt: '그래머시 태번의 입구와 간판', imageCredit: 'Wikimedia Commons · Doug Letterman · CC BY 2.0',
    duration: '1시간 30분–2시간 30분', budget: '$$$–$$$$', bestTime: '17:00대 또는 평일 점심', reservation: '다이닝룸은 28일 전 정오 공개 · 바는 워크인',
    essentials: ['다이닝룸 제철 코스', '태번 장작불 메인', '시그니처 디저트'],
    highlights: [{ title: '두 공간', text: '확실한 기념일 경험은 다이닝룸, 일정 유연성과 단품 선택은 태번이 적합하다.' }, { title: '서비스', text: '알레르기와 기념일을 예약 메모에 미리 남기면 코스 진행이 한결 자연스럽다.' }],
    transit: '4·5·6·L·N·Q·R·W선 14 St–Union Sq역에서 도보 약 7분.', routeTip: '유니언 스퀘어 그린마켓 또는 플랫아이언 산책 뒤 저녁으로 잡는다.',
    tips: ['예약 공개 시각은 뉴욕 현지 시간 기준이다.', '노쇼·취소 규정을 결제 전에 확인한다.'], tags: ['파인다이닝', '아메리칸', '기념일'],
    coordinates: { lat: 40.7383894, lng: -73.988414 }, address: '42 E 20th St, New York, NY 10003', officialUrl: 'https://www.gramercytavern.com/reservations/',
  },
  {
    id: 'atomix', category: 'food', name: '아토믹스', englishName: 'Atomix', area: '노매드 · 맨해튼',
    eyebrow: '한식의 언어를 뉴욕식 테이스팅으로 번역', summary: '재료 카드와 도자기, 서비스까지 하나의 서사로 이어지는 뉴욕 최고 수준의 한식 경험.',
    description: '셰프 카운터에서 장과 발효, 한국 식재료를 현대적으로 풀어낸 긴 코스를 선보인다. 식사 시간이 길고 가격이 높지만 뉴욕에서 진화한 한식을 보고 싶은 미식 여행자에게 독보적이다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Atomix_30th_St_2024_jeh.jpg/1920px-Atomix_30th_St_2024_jeh.jpg', imageAlt: '노매드의 아토믹스 외관', imageCredit: 'Wikimedia Commons · Jim.henderson · CC BY-SA 3.0',
    duration: '2시간 30분–3시간', budget: '$$$$', bestTime: '17:30 카운터', reservation: '2026년 9월 좌석은 매진 가능성 높음 · 취소석·공식 양도만 확인',
    essentials: ['셰프 카운터 테이스팅', '한국 술 또는 논알코올 페어링', '코스별 재료 카드'],
    highlights: [{ title: '경험 설계', text: '각 요리의 재료 카드를 읽고 맛을 비교하는 과정까지 식사의 일부다.' }, { title: '예약 판단', text: '여러 식이 제한을 모두 수용하기 어렵다. 예약 전 공식 안내와 취소 규정을 반드시 확인한다.' }],
    transit: '6선 28 St역에서 도보 약 4분, N·R·W선 28 St역에서 약 7분.', routeTip: '저녁 전 매디슨 스퀘어 파크를 가볍게 걷고 이후 일정은 비워 둔다.',
    tips: ['비공식 재판매 티켓은 피한다.', '향수는 최소화하고 정시에 도착한다.'], tags: ['한식', '테이스팅', '예약 난이도 높음'],
    coordinates: { lat: 40.7442224, lng: -73.9828456 }, address: '104 E 30th St, New York, NY 10016', officialUrl: 'https://www.atomixnyc.com/counter',
  },
  {
    id: 'sylvias', category: 'food', name: '실비아스', englishName: "Sylvia's Restaurant", area: '할렘 · 맨해튼',
    eyebrow: '할렘 소울푸드의 세대를 잇는 식탁', summary: '프라이드치킨, 바비큐 립, 콜라드그린을 가족식으로 나누는 활기찬 할렘의 클래식.',
    description: '1962년부터 같은 자리에서 이어진 소울푸드 레스토랑이다. 일요일 가스펠 브런치가 유명하지만 조용히 맛을 보려면 평일 점심이 더 편하다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Harlem_-_Sylvia%27s_Restaurant_%2848555310372%29.jpg', imageAlt: '할렘 실비아스 레스토랑의 붉은 외관', imageCredit: 'Wikimedia Commons · Ajay Suresh · CC BY 2.0',
    duration: '1시간–1시간 30분', budget: '$$–$$$', bestTime: '평일 12:00–14:00', reservation: '주말·가스펠 브런치 예약 권장',
    essentials: ['프라이드치킨', '바비큐 립 또는 캣피시', '맥앤치즈·콜라드그린·캔디드얌'],
    highlights: [{ title: '둘이 주문', text: '메인 두 개보다 프라이드치킨 하나와 사이드 세 가지를 나누면 소울푸드의 폭이 잘 보인다.' }, { title: '동네 맥락', text: '식사 전후 아폴로 극장과 숌버그 흑인문화연구센터를 함께 보면 할렘 문화사를 입체적으로 느낀다.' }],
    transit: '2·3선 125 St역에서 도보 약 3분.', routeTip: '아폴로 외관 → 실비아스 점심 → 스튜디오 뮤지엄 또는 모닝사이드 파크로 잇는다.',
    tips: ['일요일은 음악이 활기차고 대기 시간도 길다.', '사이드는 묵직하므로 한 번에 많이 주문하지 않는다.'], tags: ['소울푸드', '할렘', '역사'],
    coordinates: { lat: 40.8086285, lng: -73.9445189 }, address: '328 Malcolm X Blvd, New York, NY 10027', officialUrl: 'https://sylviasrestaurant.com/',
  },
  {
    id: 'levain-original', category: 'food', name: '르뱅 베이커리 원조점', englishName: 'Levain Bakery · Original', area: '어퍼 웨스트 사이드 · 맨해튼',
    eyebrow: '두껍고 따뜻한 뉴욕 쿠키의 원형', summary: '겉은 바삭하고 안은 촉촉한 대형 쿠키를 반으로 나눠 먹는 센트럴파크 근처 간식.',
    description: '지하층의 작은 원조점에서 시작된 뉴욕 베이커리다. 쿠키 하나가 식사에 가까울 만큼 크므로 두 명이 다른 맛 두 개를 사서 절반씩 나누는 편이 좋다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Levain%20Bakery%20-%20The%20Best%20Cookies%20in%20the%20World%20-%20Chocolate%20Chocolate%20Chip%2C%20Oatmeal%20Raisin%2C%20Chocolate%20Chip%20Walnut.jpg?width=1600', imageAlt: '르뱅 베이커리의 초콜릿·호두·오트밀 쿠키', imageCredit: 'Wikimedia Commons · Biskuit · CC BY-SA 2.0',
    duration: '15–30분', budget: '$', bestTime: '평일 09:00–11:00', reservation: '예약 불필요 · 보통 08:00–20:00 운영',
    essentials: ['초콜릿칩 월넛 쿠키', '다크초콜릿 피넛버터칩', '오트밀 레이즌'],
    highlights: [{ title: '가장 맛있을 때', text: '따뜻할 때 가운데를 갈라 서로 다른 맛을 반씩 나누면 식감 차이가 선명하다.' }, { title: '기념품', text: '당일 이동이라면 종이 봉투보다 박스 포장을 요청한다. 장거리 보관은 냉동 후 재가열한다.' }],
    transit: '1·2·3선 72 St역에서 도보 약 5분.', routeTip: '자연사박물관 → 르뱅 → 센트럴파크 레이크 또는 리버사이드 파크 산책으로 연결한다.',
    tips: ['원조점은 계단과 실내 공간이 좁다.', '견과 알레르기가 있다면 주문 전 확인한다.'], tags: ['쿠키', '디저트', '포장'],
    coordinates: { lat: 40.7799306, lng: -73.9803216 }, address: '167 W 74th St, New York, NY 10023', officialUrl: 'https://levainbakery.com/pages/west-74th-street',
  },
  {
    id: 'dominique-ansel', category: 'food', name: '도미니크 앙셀 베이커리', englishName: 'Dominique Ansel Bakery', area: '소호 · 맨해튼',
    eyebrow: '크로넛이 태어난 디저트 실험실', summary: '프랑스 페이스트리 기법과 뉴욕의 아이디어가 만나는 계절 한정 디저트 목적지.',
    description: '크루아상과 도넛을 결합한 크로넛의 원조로 매달 맛이 바뀐다. 크로넛만 좇기보다 DKA와 쿠키샷까지 둘이 나누면 이곳의 창의성을 더 잘 느낀다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Dominique_Ansel_Bakery.jpg', imageAlt: '소호 도미니크 앙셀 베이커리 입구', imageCredit: 'Wikimedia Commons · LittleT889 · CC BY-SA 4.0',
    duration: '30분–1시간', budget: '$$', bestTime: '평일 오픈 직후', reservation: '크로넛 사전 주문은 보통 월요일 11:00 ET에 2주 단위 공개',
    essentials: ['월간 크로넛', 'DKA', '쿠키샷 또는 프로즌 스모어'],
    highlights: [{ title: '현실적인 선택', text: '크로넛이 품절이어도 DKA와 계절 디저트의 완성도가 높아 방문 가치가 있다.' }, { title: '포장 판단', text: '크림이 든 제품은 당일 먹고, 선물은 비교적 이동에 강한 쿠키류를 고른다.' }],
    transit: 'C·E선 Spring St역에서 도보 약 3분, 1선 Houston St역에서 약 8분.', routeTip: '오픈 직후 디저트 → 소호 쇼핑 → 허드슨 스퀘어 순으로 남쪽에서 북쪽으로 이동한다.',
    tips: ['사전 주문과 현장 판매 수량이 다를 수 있다.', '작은 정원 좌석은 날씨와 혼잡도에 따라 이용이 어렵다.'], tags: ['크로넛', '페이스트리', '소호'],
    coordinates: { lat: 40.7251997, lng: -74.0029229 }, address: '189 Spring St, New York, NY 10012', officialUrl: 'https://www.dominiqueanselny.com/',
  },
  {
    id: 'grand-central-oyster-bar', category: 'food', name: '그랜드 센트럴 오이스터 바', englishName: 'Grand Central Oyster Bar', area: '미드타운 이스트 · 맨해튼',
    eyebrow: '1913년 역사 속에서 즐기는 동부 해산물', summary: '구아스타비노 타일 천장 아래 최대 30종의 굴과 진한 팬로스트를 맛보는 역 안의 명소.',
    description: '그랜드 센트럴 터미널 지하에 자리한 해산물 레스토랑이다. 굴 산지를 비교해 고르고 따뜻한 팬로스트를 나누면 차가운 생굴과 크리미한 국물의 대비가 좋다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Oyster_Bar.jpg', imageAlt: '아치형 타일 천장의 그랜드 센트럴 오이스터 바', imageCredit: 'Wikimedia Commons · Daniel Case · CC BY-SA 3.0',
    duration: '1시간–1시간 30분', budget: '$$$', bestTime: '평일 11:30 또는 17:00', reservation: '월–금 운영 · 2026년 기준 주말 휴무',
    essentials: ['동부 해안 생굴 모둠', '오이스터 팬로스트', '뉴잉글랜드 클램차우더'],
    highlights: [{ title: '굴 고르기', text: '서버에게 짠맛과 단맛, 크기가 다른 동부 굴 6개를 추천받아 비교한다.' }, { title: '공간', text: '아치형 구아스타비노 타일은 속삭임이 전달되는 독특한 음향을 만든다.' }],
    transit: '4·5·6·7·S선 Grand Central–42 St역, 터미널 Lower Level.', routeTip: '서밋 원 밴더빌트 또는 브라이언트 파크 → 터미널 건축 투어 → 이른 저녁으로 묶는다.',
    tips: ['주말 일정에는 넣지 않는다.', '굴 산지와 가격은 매일 바뀌므로 현장 보드를 확인한다.'], tags: ['해산물', '굴', '역사적 공간'],
    coordinates: { lat: 40.7527, lng: -73.9772 }, address: '89 E 42nd St, Lower Level, New York, NY 10017', officialUrl: 'https://grandcentralterminal.com/shop/oyster-bar-restaurant/',
  },

  // SIGHTS · 10
  {
    id: 'central-park-bethesda', category: 'sights', name: '센트럴파크 베데스다 테라스', englishName: 'Bethesda Terrace & The Mall', area: '센트럴파크 · 맨해튼',
    eyebrow: '영화 속 뉴욕을 걷는 공원의 중심', summary: '아치형 회랑과 느릅나무 길, 호수가 한 장면에 이어지는 센트럴파크의 대표 산책.',
    description: '59번가에서 곧장 횡단하기보다 더 몰, 베데스다 테라스, 더 레이크를 한 방향으로 잇는 코스가 편하다. 공원 전체를 욕심내지 않아도 뉴욕의 녹지와 건축을 충분히 느낀다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Bethesda_Fountain_and_the_Lake%2C_Central_Park%2C_Manhattan%2C_New_York.jpg/1920px-Bethesda_Fountain_and_the_Lake%2C_Central_Park%2C_Manhattan%2C_New_York.jpg', imageAlt: '센트럴파크 베데스다 테라스와 분수', imageCredit: 'Wikimedia Commons · Christian David · CC BY-SA 4.0',
    duration: '1시간 30분–2시간 30분', budget: '무료', bestTime: '평일 08:00–10:00', reservation: '예약 불필요 · 분수는 2026년 8월부터 약 1년간 가동 중단',
    essentials: ['더 몰 느릅나무 길', '베데스다 아케이드 타일', '더 레이크 보트하우스 전망'],
    highlights: [{ title: '2026년 현장', text: '베데스다 테라스와 아케이드는 열려 있지만 분수는 약 1년간 복원 공사로 가동하지 않는다.' }, { title: '편한 동선', text: '남쪽 더 몰에서 북쪽 테라스로 내려간 뒤 호숫가까지만 보고 72 St에서 빠져나오면 경사가 적다.' }],
    transit: 'N·R·W선 5 Av/59 St역 또는 A·B·C선 72 St역. 출발 방향에 맞춰 선택.', routeTip: '오전 공원 → 어퍼 웨스트 사이드 점심 → 메트 또는 자연사박물관 중 하나로 연결한다.',
    tips: ['공원 내 길은 비슷해 보이므로 오프라인 지도를 저장한다.', '벤치가 많아 30분마다 짧게 쉬기 좋다.'], tags: ['공원', '영화 촬영지', '가벼운 산책'],
    coordinates: { lat: 40.774, lng: -73.9709 }, address: 'Bethesda Terrace, Central Park, New York, NY 10024', officialUrl: 'https://www.centralparknyc.org/locations/bethesda-terrace',
  },
  {
    id: 'high-line', category: 'sights', name: '하이라인', englishName: 'The High Line', area: '첼시·미트패킹 · 맨해튼',
    eyebrow: '철길 위에 만든 뉴욕의 선형 공원', summary: '오래된 고가 화물철도를 따라 정원, 공공미술, 허드슨강과 건물 사이를 걷는 도시 산책.',
    description: '남쪽 갠즈보트 스트리트부터 북쪽 허드슨야즈까지 약 2.3km 이어진다. 전 구간보다 첼시마켓 인근에서 26번가까지 핵심 구간만 걸으면 체력 부담이 적다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/High_Line_td_%282023-06-23%29_020_-_30th_Street_Spur.jpg/1920px-High_Line_td_%282023-06-23%29_020_-_30th_Street_Spur.jpg', imageAlt: '식재와 옛 철길이 어우러진 하이라인', imageCredit: 'Wikimedia Commons · Tdorante10 · CC BY-SA 4.0',
    duration: '1시간 30분–2시간', budget: '무료', bestTime: '평일 08:00–10:00 또는 일몰 전', reservation: '예약 불필요 · 특별 프로그램은 별도',
    essentials: ['10th Avenue Square', '첼시 건축 파사드', '허드슨강 일몰'],
    highlights: [{ title: '짧은 버전', text: '14 St 엘리베이터로 올라 26 St까지 북상하면 대표 풍경을 보고 혼잡한 허드슨야즈 구간은 생략할 수 있다.' }, { title: '도시 읽기', text: '옛 레일과 자생식물, 새 건축이 같은 높이에서 겹쳐 보여 뉴욕 재생 프로젝트의 성격이 선명하다.' }],
    transit: 'A·C·E·L선 14 St–8 Av역에서 남단까지 도보 약 8분. 14 St에 엘리베이터.', routeTip: '첼시마켓 점심 → 하이라인 북상 → 허드슨야즈에서 지하철로 복귀한다.',
    tips: ['오후와 주말은 통로가 매우 붐빈다.', '화장실 위치가 드물어 첼시마켓에서 미리 이용한다.'], tags: ['도시재생', '공공미술', '산책'],
    coordinates: { lat: 40.7466, lng: -74.0058 }, address: 'Gansevoort St to 34th St, Manhattan, NY', officialUrl: 'https://www.thehighline.org/',
  },
  {
    id: 'brooklyn-bridge-dumbo', category: 'sights', name: '브루클린 브리지와 덤보', englishName: 'Brooklyn Bridge & DUMBO', area: '로어 맨해튼·덤보',
    eyebrow: '뉴욕 스카이라인을 향해 걷는 가장 상징적인 길', summary: '석조 교각과 케이블 사이를 건너 워싱턴 스트리트, 브리지 파크 수변까지 이어지는 반나절.',
    description: '맨해튼에서 브루클린으로 건너면 진행 방향 앞에 덤보와 공원이 이어져 동선이 자연스럽다. 다리 왕복 대신 편도로 걷고 지하철로 돌아오면 체력을 아낀다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Brooklyn_Bridge_Park_td_%282019-08-23%29_019_-_Pier_1%2C_Brooklyn_Bridge.jpg/1920px-Brooklyn_Bridge_Park_td_%282019-08-23%29_019_-_Pier_1%2C_Brooklyn_Bridge.jpg', imageAlt: '이스트강 위 브루클린 브리지와 맨해튼 스카이라인', imageCredit: 'Wikimedia Commons · Tdorante10 · CC BY-SA 4.0',
    duration: '2시간 30분–4시간', budget: '무료–$', bestTime: '평일 일출 후 또는 일몰 90분 전', reservation: '예약 불필요',
    essentials: ['브리지 보행로 교각', '워싱턴 스트리트 맨해튼 브리지 뷰', '브루클린 브리지 파크 피어 1'],
    highlights: [{ title: '방향 선택', text: 'City Hall 쪽에서 진입해 브루클린 방향으로 편도 이동하면 덤보 관광과 지하철 복귀가 쉽다.' }, { title: '사진 이후', text: '워싱턴 스트리트는 짧게 보고 강변으로 내려가면 다리 두 개와 스카이라인을 동시에 본다.' }],
    transit: '맨해튼 진입은 4·5·6선 Brooklyn Bridge–City Hall역. 복귀는 A·C선 High St역.', routeTip: '오전 브리지 횡단 → 덤보 점심 → 피어 1에서 페리 또는 지하철로 복귀한다.',
    tips: ['자전거 차로와 보행로 표시를 따른다.', '그늘이 거의 없어 한낮은 피한다.'], tags: ['브리지', '스카이라인', '사진'],
    coordinates: { lat: 40.7061, lng: -73.9969 }, address: 'Brooklyn Bridge, New York, NY 10038', officialUrl: 'https://www.nyc.gov/html/dot/html/infrastructure/brooklyn-bridge.shtml',
  },
  {
    id: 'statue-liberty-ellis', category: 'sights', name: '자유의 여신상과 엘리스섬', englishName: 'Statue of Liberty & Ellis Island', area: '뉴욕항',
    eyebrow: '이민과 자유의 서사를 품은 뉴욕항', summary: '페리를 타고 자유의 여신상 가까이 다가가 엘리스섬 이민박물관까지 보는 미국사의 핵심 하루.',
    description: '공식 페리 티켓 하나로 리버티섬과 엘리스섬을 방문한다. 왕관이나 페데스털보다 섬 산책과 이민박물관에 집중하면 예약 부담과 계단을 줄일 수 있다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Statue_of_Liberty_frontal_2.jpg/1920px-Statue_of_Liberty_frontal_2.jpg', imageAlt: '뉴욕항의 자유의 여신상', imageCredit: 'Wikimedia Commons · Daniel Schwen · Public Domain',
    duration: '4시간 30분–6시간', budget: '$$', bestTime: '첫 1–2회 페리', reservation: '공식 페리 사전 예매 · 왕관은 수개월 전 매진 가능',
    essentials: ['리버티섬 산책', '엘리스섬 이민박물관', '페리 위 로어 맨해튼 전망'],
    highlights: [{ title: '티켓 구분', text: '일반 입장, 페데스털, 왕관 티켓의 접근 범위가 다르다. 체력 부담을 줄이면 일반 입장도 충분하다.' }, { title: '보안', text: '탑승 전 공항 수준의 보안 검색이 있어 큰 가방과 금지 물품을 숙소에 둔다.' }],
    transit: '1선 South Ferry역 또는 4·5선 Bowling Green역에서 Battery Park 공식 선착장으로 이동.', routeTip: '오전 섬 방문 뒤 배터리파크 → 월스트리트 → 9·11 메모리얼로 북상한다.',
    tips: ['길거리 호객이 아닌 공식 운영사 링크만 이용한다.', '바람이 강하므로 겉옷과 멀미 대비를 준비한다.'], tags: ['미국 역사', '페리', '예약'],
    coordinates: { lat: 40.6892, lng: -74.0445 }, address: 'Liberty Island, New York, NY 10004', officialUrl: 'https://www.nps.gov/stli/planyourvisit/index.htm',
  },
  {
    id: 'top-of-the-rock', category: 'sights', name: '탑 오브 더 록', englishName: 'Top of the Rock', area: '록펠러센터 · 맨해튼',
    eyebrow: '엠파이어 스테이트 빌딩이 보이는 클래식 전망대', summary: '센트럴파크와 미드타운을 야외 테라스에서 함께 보는 균형 좋은 스카이라인 전망.',
    description: '세 층의 전망 공간 중 상부 야외 데크는 유리 반사 없이 사진을 찍기 좋다. 서쪽 일몰만 기다리기보다 낮과 야경이 바뀌는 60–90분을 잡는다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/NYC_Top_of_the_Rock_Pano.jpg/1920px-NYC_Top_of_the_Rock_Pano.jpg', imageAlt: '탑 오브 더 록에서 본 미드타운 스카이라인', imageCredit: 'Wikimedia Commons · Daniel Schwen · CC BY-SA 3.0',
    duration: '1시간 30분–2시간', budget: '$$$', bestTime: '일몰 60분 전 입장', reservation: '시간 지정 사전 예매 권장',
    essentials: ['67–70층 전망대', '엠파이어 스테이트 빌딩 정면 뷰', '센트럴파크 북쪽 전망'],
    highlights: [{ title: '이 전망대를 고를 이유', text: '뉴욕의 대표 실루엣인 엠파이어 스테이트 빌딩을 풍경 안에 담을 수 있다.' }, { title: '추가 체험 판단', text: '빔·스카이리프트 등 유료 옵션은 높은 곳을 불편해하면 생략해도 기본 전망의 만족도가 충분하다.' }],
    transit: 'B·D·F·M선 47–50 Sts–Rockefeller Center역에서 실내 통로로 접근.', routeTip: 'MoMA → 5번가 산책 → 록펠러센터 이른 저녁 → 전망대로 연결한다.',
    tips: ['일몰 시간대는 추가 요금과 대기가 생길 수 있다.', '삼각대와 큰 가방 제한을 확인한다.'], tags: ['전망대', '일몰', '미드타운'],
    coordinates: { lat: 40.7593, lng: -73.9794 }, address: '30 Rockefeller Plaza, New York, NY 10112', officialUrl: 'https://www.rockefellercenter.com/attractions/top-of-the-rock-observation-deck/',
  },
  {
    id: 'empire-state-building', category: 'sights', name: '엠파이어 스테이트 빌딩', englishName: 'Empire State Building Observatory', area: '미드타운 사우스 · 맨해튼',
    eyebrow: '아르데코 뉴욕의 아이콘 안으로', summary: '1931년의 아르데코 로비와 몰입형 전시를 지나 86층 야외 전망대에 서는 정석 뉴욕 경험.',
    description: '전망만 보는 곳이 아니라 건설 역사와 영화 속 장면을 보여주는 전시가 입장 동선에 포함된다. 야외 86층까지가 핵심이고 102층 업그레이드는 예산에 따라 선택한다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Empire%20State%20Building%20from%20the%20Top%20of%20the%20Rock.jpg?width=1600', imageAlt: '미드타운 위로 솟은 엠파이어 스테이트 빌딩', imageCredit: 'Wikimedia Commons · Sam Valadi · CC BY 2.0',
    duration: '1시간 30분–2시간', budget: '$$$–$$$$', bestTime: '개장 직후 또는 21:00 이후', reservation: '시간 지정 예매 권장',
    essentials: ['아르데코 로비', '2층 역사 전시', '86층 야외 데크'],
    highlights: [{ title: '시야', text: '다운타운과 플랫아이언 축이 선명하고 사방으로 열린 야외 난간에서 도시 소리를 함께 듣는다.' }, { title: '선택 기준', text: '아이콘 자체에 올라가는 의미는 크지만 건물 외관 사진은 탑 오브 더 록에서 더 잘 보인다.' }],
    transit: 'B·D·F·M·N·Q·R·W선 34 St–Herald Sq역에서 도보 약 5분.', routeTip: '모건 라이브러리 → 코리아타운 식사 → 늦은 시간 전망대로 혼잡을 피한다.',
    tips: ['날씨가 흐리면 공식 가시거리 안내를 확인한다.', '야외층은 지상보다 바람이 강하다.'], tags: ['아르데코', '전망대', '야간'],
    coordinates: { lat: 40.7484, lng: -73.9857 }, address: '20 W 34th St, New York, NY 10001', officialUrl: 'https://www.esbnyc.com/',
  },
  {
    id: 'grand-central-terminal', category: 'sights', name: '그랜드 센트럴 터미널', englishName: 'Grand Central Terminal', area: '미드타운 이스트 · 맨해튼',
    eyebrow: '별자리 천장 아래 살아 움직이는 도시', summary: '보자르 건축, 오팔 시계, 위스퍼링 갤러리가 실제 통근 동선과 겹치는 뉴욕의 관문.',
    description: '랜드마크이면서 매일 쓰이는 역이라 짧은 시간에도 뉴욕의 규모와 리듬을 읽기 좋다. 메인 콩코스만 보고 끝내지 말고 아래층 타일 아치와 식음 공간까지 내려간다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Grand_Central_Station_Main_Concourse_Rectilinear_projection_Jan_2006.jpg/1920px-Grand_Central_Station_Main_Concourse_Rectilinear_projection_Jan_2006.jpg', imageAlt: '별자리 천장과 오팔 시계가 있는 그랜드 센트럴 메인 콩코스', imageCredit: 'Wikimedia Commons · Diliff · CC BY 2.5',
    duration: '45분–1시간 30분', budget: '무료–$', bestTime: '평일 10:00–15:00', reservation: '자유 관람은 예약 불필요 · 공식 투어는 사전 예약',
    essentials: ['메인 콩코스 오팔 시계', '별자리 천장', '위스퍼링 갤러리'],
    highlights: [{ title: '천장의 비밀', text: '별자리 방향과 작은 검은 얼룩 등 복원 과정의 이야기를 알고 보면 공간이 더 풍부해진다.' }, { title: '소리 체험', text: '오이스터 바 앞 아치의 대각선 모서리에 둘이 서서 벽을 향해 말하면 속삭임이 전달된다.' }],
    transit: '4·5·6·7·S선 Grand Central–42 St역과 직접 연결.', routeTip: '브라이언트 파크 → 크라이슬러 빌딩 외관 → 터미널 → 서밋 원 밴더빌트를 한 블록 축으로 묶는다.',
    tips: ['통근 시간에는 중앙 흐름을 막지 않는다.', '발코니에서 내려다보면 공간 전체를 한눈에 보기 좋다.'], tags: ['건축', '무료', '실내'],
    coordinates: { lat: 40.7527, lng: -73.9772 }, address: '89 E 42nd St, New York, NY 10017', officialUrl: 'https://grandcentralterminal.com/',
  },
  {
    id: 'roosevelt-tram', category: 'sights', name: '루스벨트 아일랜드 트램', englishName: 'Roosevelt Island Tramway', area: '어퍼 이스트 사이드·루스벨트 아일랜드',
    eyebrow: '지하철 요금으로 건너는 이스트강 공중 산책', summary: '퀸즈버러 브리지 옆을 천천히 오르며 미드타운 스카이라인을 보는 짧고 강렬한 이동.',
    description: '관광 어트랙션처럼 보이지만 실제 대중교통이다. 맨해튼에서 약 4분 만에 섬으로 건너가고 남쪽 수변 산책로와 포 프리덤스 파크를 더하면 편안한 반나절이 된다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Roosevelt_Island_tramcar_2010.jpg/1920px-Roosevelt_Island_tramcar_2010.jpg', imageAlt: '이스트강 위를 지나는 루스벨트 아일랜드 트램', imageCredit: 'Wikimedia Commons · Jim.henderson · CC BY-SA 3.0',
    duration: '왕복 포함 2–3시간', budget: '$', bestTime: '일몰 60분 전', reservation: '예약 불필요 · OMNY 결제',
    essentials: ['트램 창가 스카이라인', '사우스포인트 파크', '포 프리덤스 파크'],
    highlights: [{ title: '뷰 포인트', text: '맨해튼 출발 때 진행 방향 오른쪽, 돌아올 때 왼쪽이 미드타운 전망에 유리하다.' }, { title: '피로도', text: '섬 남쪽만 왕복하면 평지 위주다. 귀로에는 F선이나 NYC Ferry를 선택할 수 있다.' }],
    transit: 'N·R·W선 Lexington Av/59 St역에서 트램 승강장까지 도보 약 5분.', routeTip: '오전 MoMA 또는 5번가와 묶고 해 질 무렵 트램과 섬 산책으로 마무리한다.',
    tips: ['출퇴근 시간에는 통근객을 위해 문 주변을 비운다.', '강바람에 대비해 얇은 겉옷을 챙긴다.'], tags: ['전망', '가벼운 산책', '가성비'],
    coordinates: { lat: 40.7616, lng: -73.9644 }, address: 'E 60th St & 2nd Ave, New York, NY 10022', officialUrl: 'https://rioc.ny.gov/302/Tram',
  },
  {
    id: 'nine-eleven-oculus', category: 'sights', name: '9·11 메모리얼과 오큘러스', englishName: '9/11 Memorial & Oculus', area: '월드 트레이드 센터 · 맨해튼',
    eyebrow: '기억의 빈자리와 미래형 교통 허브', summary: '쌍둥이 빌딩의 흔적을 담은 두 개의 반사 연못과 흰 갈비뼈 같은 오큘러스를 함께 본다.',
    description: '메모리얼 플라자는 무료 야외 공간이고 박물관은 별도 티켓이 필요하다. 가볍게 방문하면 연못과 생존자 나무, 오큘러스의 대비를 90분 안에 볼 수 있다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/September_11_Memorial_in_New_York.jpg/1920px-September_11_Memorial_in_New_York.jpg', imageAlt: '9·11 메모리얼 추모 수조와 맨해튼 스카이라인', imageCredit: 'Wikimedia Commons · Tiraspolsky · CC BY-SA 4.0',
    duration: '1시간 30분–3시간', budget: '무료–$$', bestTime: '평일 09:00–11:00', reservation: '메모리얼 플라자는 예약 불필요 · 박물관은 시간 지정권 권장',
    essentials: ['북·남쪽 반사 연못', '생존자 나무', '오큘러스 중앙축'],
    highlights: [{ title: '방문 태도', text: '메모리얼은 희생자 추모 공간이다. 사진보다 이름과 장소의 맥락을 천천히 읽는다.' }, { title: '박물관 선택', text: '전시 내용이 무겁고 2시간 이상 필요하다. 같은 날 공연 전에는 플라자만 보는 선택도 합리적이다.' }],
    transit: 'E선 World Trade Center역, R·W선 Cortlandt St역, 1선 WTC Cortlandt역과 연결.', routeTip: '오큘러스 → 메모리얼 → 리버티파크 → 배터리파크 방향으로 남하한다.',
    tips: ['박물관 내부 촬영 제한을 따른다.', '오큘러스는 쇼핑몰이자 역이므로 출구 번호를 확인한다.'], tags: ['역사', '건축', '실내외'],
    coordinates: { lat: 40.7115, lng: -74.0134 }, address: '180 Greenwich St, New York, NY 10007', officialUrl: 'https://www.911memorial.org/',
  },
  {
    id: 'little-island', category: 'sights', name: '리틀 아일랜드', englishName: 'Little Island', area: '허드슨 리버 파크 · 맨해튼',
    eyebrow: '튤립 모양 기둥 위에 띄운 작은 공원', summary: '완만한 언덕과 정원, 강변 전망을 한 시간 안에 즐기는 접근성 좋은 현대적 수변 공간.',
    description: '132개의 콘크리트 기둥 위에 만든 인공섬 공원으로 짧은 오르막마다 허드슨강과 맨해튼의 시야가 달라진다. 엘리베이터와 완만한 경로가 있어 체력 부담이 낮다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/At_New_York_City_2023_060_-_Little_Island_at_Pier_55.jpg/1920px-At_New_York_City_2023_060_-_Little_Island_at_Pier_55.jpg', imageAlt: '허드슨강 위 리틀 아일랜드와 튤립 모양 기둥', imageCredit: 'Wikimedia Commons · Mike Peel · CC BY-SA 4.0',
    duration: '45분–1시간 30분', budget: '무료', bestTime: '일몰 45분 전', reservation: '일반 입장은 예약 불필요 · 공연은 별도 예매',
    essentials: ['사우스 전망대', '계절 정원', '앰피시어터 강변 뷰'],
    highlights: [{ title: '가장 편한 길', text: '입구에서 완만한 외곽 램프를 따라 전망대로 올라가고 중앙 정원으로 내려오면 급한 계단을 피한다.' }, { title: '함께 보기', text: '하이라인 남단과 첼시마켓이 가까워 별도 이동 없이 세 공간을 이어 볼 수 있다.' }],
    transit: 'A·C·E·L선 14 St–8 Av역에서 도보 약 12분. M11 버스가 강변과 가깝다.', routeTip: '첼시마켓 → 하이라인 짧은 구간 → 리틀 아일랜드 일몰 순서가 자연스럽다.',
    tips: ['강풍이나 행사로 일부 구역이 닫힐 수 있다.', '노을 직전은 붐비므로 벤치보다 전망 동선을 먼저 돈다.'], tags: ['수변', '현대건축', '일몰'],
    coordinates: { lat: 40.742, lng: -74.0106 }, address: 'Pier 55, W 13th St, New York, NY 10014', officialUrl: 'https://littleisland.org/',
  },

  // CULTURE · 10
  {
    id: 'broadway', category: 'culture', name: '브로드웨이 뮤지컬', englishName: 'Broadway Theatre District', area: '시어터 디스트릭트 · 맨해튼',
    eyebrow: '뉴욕의 밤을 완성하는 라이브 스테이지', summary: '배우의 호흡, 오케스트라, 오래된 극장의 밀도를 한꺼번에 경험하는 뉴욕의 대표 문화.',
    description: '브로드웨이는 하나의 극장이 아니라 타임스스퀘어 일대의 전문 극장가를 뜻한다. 관심 작품을 추린 뒤 좌석과 시간대를 비교하면 여행 동선과 예산을 짜기 쉽다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Various_Pictures_from_New_York_City_-_September%2C_2025.jpg/1920px-Various_Pictures_from_New_York_City_-_September%2C_2025.jpg', imageAlt: '브로드웨이 극장가의 공연 간판과 거리', imageCredit: 'Wikimedia Commons · Corey Seeman · CC BY-SA 4.0',
    duration: '2시간 30분–3시간', budget: '$$$–$$$$', bestTime: '화–목 저녁 공연', reservation: '인기작 공식 판매처 사전 예매',
    essentials: ['관심 작품의 공식 좌석표', '막간 포함 종료 시각', '극장 입구 사전 확인'],
    highlights: [{ title: '좌석 선택', text: '대형 뮤지컬은 오케스트라 중후반 또는 메자닌 전면이 무대 전체를 보기 편하다.' }, { title: '저녁 동선', text: '공연 90분 전 식사를 시작하고 30분 전 극장에 도착하면 티켓 확인과 화장실 이용이 여유롭다.' }],
    transit: '1·2·3·7·N·Q·R·W·S선 Times Sq–42 St역. 극장은 41–54 St 사이에 흩어져 있다.', routeTip: '오후 미드타운 관람 → 17시대 저녁 → 19시 또는 20시 공연 순서가 안정적이다.',
    tips: ['작품 공식 사이트가 연결한 판매처를 사용한다.', '극장 내부는 계단과 좌석 간격이 좁은 편이다.'], tags: ['뮤지컬', '야간', '예약'],
    coordinates: { lat: 40.758, lng: -73.9855 }, address: 'Theater District, New York, NY 10036', officialUrl: 'https://www.broadway.org/',
  },
  {
    id: 'the-met', category: 'culture', name: '메트로폴리탄 미술관', englishName: 'The Metropolitan Museum of Art', area: '뮤지엄 마일 · 맨해튼',
    eyebrow: '5천 년의 예술을 품은 뉴욕의 거대한 방', summary: '이집트 신전부터 유럽 회화와 미국 장식미술까지, 세 작품군만 골라도 하루의 밀도가 높다.',
    description: '모든 전시실을 보려 하면 쉽게 지친다. 덴두르 신전, 유럽 회화, 미국관처럼 서로 다른 세 구역을 선택하고 중간에 카페나 옥상에서 쉬는 방식이 좋다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Metropolitan_Museum_of_Art_entrance_NYC.JPG', imageAlt: '5번가의 메트로폴리탄 미술관 정면', imageCredit: 'Wikimedia Commons · Arad · CC BY-SA 3.0',
    duration: '3–4시간', budget: '$$', bestTime: '개장 직후 또는 금·토 늦은 오후', reservation: '온라인 티켓 권장 · 보통 수요일 휴관',
    essentials: ['덴두르 신전', '유럽 회화 핵심실', '미국관 찰스 엥겔하드 코트'],
    highlights: [{ title: '3구역 원칙', text: '입장 직후 지도를 보고 꼭 볼 구역 세 곳만 표시하면 이동과 피로가 크게 줄어든다.' }, { title: '공원과 함께', text: '동쪽 출입구에서 나와 센트럴파크 보트 연못까지 20분만 걸어도 실내 관람의 답답함이 풀린다.' }],
    transit: '4·5·6선 86 St역에서 도보 약 12분, M1·M2·M3·M4 버스가 5번가를 지난다.', routeTip: '오전 메트 3시간 → 공원 벤치 휴식 → 매디슨 애비뉴 카페로 마무리한다.',
    tips: ['뉴욕주 거주자 선택 요금은 관광객에게 적용되지 않는다.', '큰 가방 보관과 옥상 운영 여부를 당일 확인한다.'], tags: ['고전미술', '뮤지엄 마일', '반나절'],
    coordinates: { lat: 40.7794, lng: -73.9632 }, address: '1000 5th Ave, New York, NY 10028', officialUrl: 'https://www.metmuseum.org/',
  },
  {
    id: 'moma', category: 'culture', name: '뉴욕 현대미술관', englishName: 'The Museum of Modern Art', area: '미드타운 · 맨해튼',
    eyebrow: '현대미술의 교과서를 실제 크기로', summary: '반 고흐, 피카소, 마티스부터 사진과 디자인까지 익숙한 이미지의 원작을 만나는 미술관.',
    description: '5층에서 4층으로 내려오며 1880년대부터 1940년대 대표작을 먼저 보면 흐름이 잘 잡힌다. 모든 층을 돌기보다 회화·디자인·조각정원을 중심으로 선택한다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Museum_of_Modern_Art%2C_New_York_City_-_panoramio.jpg', imageAlt: '뉴욕 현대미술관의 53번가 입구', imageCredit: 'Wikimedia Commons · Colin W · CC BY-SA 3.0',
    duration: '2시간 30분–3시간 30분', budget: '$$', bestTime: '평일 개장 직후', reservation: '시간 지정 티켓 권장',
    essentials: ['5층 컬렉션 갤러리', '애비 앨드리치 록펠러 조각정원', '건축·디자인 컬렉션'],
    highlights: [{ title: '방향', text: '에스컬레이터로 5층까지 올라간 뒤 한 층씩 내려오면 인기작을 비교적 덜 지친 상태로 본다.' }, { title: '디자인 쇼핑', text: '미술관 관람 뒤 소호 또는 53번가 디자인 스토어에서 컬렉션 기반 소품을 이어 볼 수 있다.' }],
    transit: 'E·M선 5 Av/53 St역 또는 B·D·F·M선 47–50 Sts역에서 도보 약 5분.', routeTip: 'MoMA → 5번가 건축 산책 → 록펠러센터 전망 또는 재즈 공연으로 잇는다.',
    tips: ['별이 빛나는 밤 주변은 혼잡하므로 먼저 본다.', '오디오 가이드는 개인 이어폰을 준비한다.'], tags: ['현대미술', '디자인', '실내'],
    coordinates: { lat: 40.7614, lng: -73.9776 }, address: '11 W 53rd St, New York, NY 10019', officialUrl: 'https://www.moma.org/',
  },
  {
    id: 'whitney', category: 'culture', name: '휘트니 미술관', englishName: 'Whitney Museum of American Art', area: '미트패킹 · 맨해튼',
    eyebrow: '미국 현대미술과 허드슨강이 만나는 테라스', summary: '20·21세기 미국미술을 층별 야외 테라스와 함께 보는 가볍고 선명한 미술관 경험.',
    description: '렌조 피아노 건물의 동쪽 갤러리와 서쪽 테라스를 번갈아 이동해 관람 피로가 덜하다. 하이라인 남단 바로 옆이라 미술과 산책을 자연스럽게 묶는다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Whitney_Museum_and_end_of_High_Line.jpg/1920px-Whitney_Museum_and_end_of_High_Line.jpg', imageAlt: '하이라인 남단에서 본 휘트니 미술관', imageCredit: 'Wikimedia Commons · Beyond My Ken · CC BY-SA 4.0',
    duration: '2–3시간', budget: '$$', bestTime: '개장 직후 또는 금요일 저녁', reservation: '시간 지정권 권장 · 보통 화요일 휴관',
    essentials: ['미국미술 컬렉션', '층별 야외 테라스', '허드슨강 전망'],
    highlights: [{ title: '건물 즐기기', text: '계단식 야외 테라스로 한 층씩 내려오면 스카이라인과 작품을 번갈아 보며 쉰다.' }, { title: '저녁 프로그램', text: '무료 또는 할인 시간대는 예약이 빨리 찬다. 공식 일정에서 조건과 입장 시간을 확인한다.' }],
    transit: 'A·C·E·L선 14 St–8 Av역에서 도보 약 10분.', routeTip: '휘트니 → 하이라인 짧은 구간 → 첼시마켓 이른 저녁으로 이동한다.',
    tips: ['기획전 교체기에는 일부 층이 닫힐 수 있다.', '테라스는 비와 강풍 때 제한될 수 있다.'], tags: ['미국미술', '건축', '하이라인'],
    coordinates: { lat: 40.7396, lng: -74.0089 }, address: '99 Gansevoort St, New York, NY 10014', officialUrl: 'https://whitney.org/',
  },
  {
    id: 'guggenheim', category: 'culture', name: '솔로몬 R. 구겐하임 미술관', englishName: 'Solomon R. Guggenheim Museum', area: '뮤지엄 마일 · 맨해튼',
    eyebrow: '프랭크 로이드 라이트의 나선형 미술관', summary: '작품과 관람객이 하나의 경사로를 따라 흐르는, 건물 자체가 가장 강렬한 전시인 공간.',
    description: '엘리베이터로 위층에 올라 완만한 램프를 따라 내려오면 체력 소모가 적다. 기획전 설치 기간에는 나선형 로툰다 접근이 제한될 수 있어 방문 전 확인이 중요하다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Solomon_R._Guggenheim_Museum_%2848059131351%29.jpg/1920px-Solomon_R._Guggenheim_Museum_%2848059131351%29.jpg', imageAlt: '구겐하임 미술관의 흰색 나선형 외관', imageCredit: 'Wikimedia Commons · Ajay Suresh · CC BY 2.0',
    duration: '1시간 30분–2시간 30분', budget: '$$', bestTime: '개장 직후', reservation: '시간 지정권 권장 · 전시 설치 일정 확인',
    essentials: ['로툰다 나선형 램프', '탄하우저 컬렉션', '5번가 외관 곡선'],
    highlights: [{ title: '관람 순서', text: '엘리베이터로 상단 이동 후 아래로 내려오면 작품과 건축의 흐름을 자연스럽게 읽는다.' }, { title: '사진', text: '로툰다 중앙에서 천창을 올려다보고 층마다 곡선 난간의 구도가 달라지는지 비교한다.' }],
    transit: '4·5·6선 86 St역에서 도보 약 10분. M1·M2·M3·M4 버스가 더 가깝다.', routeTip: '구겐하임 2시간 → 재클린 케네디 저수지 산책 → 카페 휴식으로 끝낸다.',
    tips: ['나선형 바닥은 완만하지만 계속 경사져 있다.', '대형 가방 정책과 전시실 촬영 규정을 확인한다.'], tags: ['건축', '현대미술', '뮤지엄 마일'],
    coordinates: { lat: 40.783, lng: -73.959 }, address: '1071 5th Ave, New York, NY 10128', officialUrl: 'https://www.guggenheim.org/',
  },
  {
    id: 'amnh', category: 'culture', name: '미국 자연사박물관', englishName: 'American Museum of Natural History', area: '어퍼 웨스트 사이드 · 맨해튼',
    eyebrow: '공룡에서 우주까지 이어지는 미국식 스케일', summary: '거대한 공룡 화석, 생물 다양성 홀, 천문관을 한 건물에서 만나는 몰입형 박물관.',
    description: '건물이 매우 커서 공룡, 해양생물, 길더 센터 등 세 구역만 고르는 것이 좋다. 최신 과학 공간과 오래된 디오라마의 시대감이 함께 있어 미국 박물관 문화도 보인다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/AMNH-exterior.jpg?width=1600', imageAlt: '센트럴파크 웨스트의 미국 자연사박물관', imageCredit: 'Wikimedia Commons · Captain-tucker · CC BY-SA 3.0',
    duration: '3–4시간', budget: '$$–$$$', bestTime: '개장 직후', reservation: '시간 지정 티켓 권장 · 특별전 별도',
    essentials: ['티라노사우루스와 공룡홀', '블루웨일 밀스타인 홀', '길더 센터 또는 헤이든 천문관'],
    highlights: [{ title: '성인 관람법', text: '아이 중심 시설로만 생각하지 말고 진화·우주·건축이라는 세 주제로 골라 보면 밀도가 높다.' }, { title: '동선', text: '81 St 지하철 연결 입구로 들어가 위층 공룡부터 본 뒤 아래로 내려오면 이동이 편하다.' }],
    transit: 'B·C선 81 St–Museum of Natural History역과 직접 연결.', routeTip: '박물관 오전 → 어퍼 웨스트 사이드 점심 → 센트럴파크 서쪽 짧은 산책으로 잇는다.',
    tips: ['일반권과 특별전 포함권을 구분한다.', '관내 지도가 복잡하므로 만나기로 한 출구를 미리 정한다.'], tags: ['공룡', '과학', '우천 추천'],
    coordinates: { lat: 40.7813, lng: -73.974 }, address: '200 Central Park W, New York, NY 10024', officialUrl: 'https://www.amnh.org/',
  },
  {
    id: 'apollo-theater', category: 'culture', name: '아폴로 극장과 할렘 문화 산책', englishName: 'Apollo Theater & Harlem', area: '할렘 · 맨해튼',
    eyebrow: '미국 흑인 대중문화의 상징적인 무대', summary: '엘라 피츠제럴드와 제임스 브라운의 역사가 시작된 극장을 중심으로 125번가 문화를 읽는다.',
    description: '아폴로의 역사적 본관은 2026년 리노베이션으로 닫혀 있고 재개장은 2026년 말로 예정돼 있다. 이 시기 공연은 인근 빅토리아의 Apollo Stages에서 열리므로 장소를 반드시 구분한다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Apollo_Theatre_from_west.jpg/1920px-Apollo_Theatre_from_west.jpg', imageAlt: '할렘 125번가 아폴로 극장의 간판', imageCredit: 'Wikimedia Commons · Beyond My Ken · CC BY-SA 4.0',
    duration: '외관·동네 1시간 30분, 공연 2–3시간', budget: '무료–$$$', bestTime: '낮 문화 산책 또는 공연 저녁', reservation: '본관 2026년 공사 중 · 투어·공연은 공식 장소와 시간 확인',
    essentials: ['역사적 본관 외관', 'Walk of Fame 명판', 'Apollo Stages 공연 일정'],
    highlights: [{ title: '2026년 주의', text: '본관에서 공연을 볼 수 있다고 가정하지 않는다. 티켓에 적힌 The Victoria 주소를 지도에 따로 저장한다.' }, { title: '동네와 함께', text: '실비아스와 숌버그 흑인문화연구센터, 125번가를 연결하면 극장 외관만 보는 아쉬움을 줄인다.' }],
    transit: '2·3선 125 St역에서 본관까지 도보 약 3분.', routeTip: '아폴로 외관 → 실비아스 점심 → 숌버그 흑인문화연구센터 또는 모닝사이드 파크로 이어 간다.',
    tips: ['비공식 길거리 공연 호객을 피한다.', '공연장 주소와 입장 마감 시간을 티켓에서 재확인한다.'], tags: ['할렘', '음악사', '2026 공사'],
    coordinates: { lat: 40.81, lng: -73.9501 }, address: '253 W 125th St, New York, NY 10027', officialUrl: 'https://www.apollotheater.org/',
  },
  {
    id: 'jazz-at-lincoln-center', category: 'culture', name: '재즈 앳 링컨 센터', englishName: 'Jazz at Lincoln Center', area: '콜럼버스 서클 · 맨해튼',
    eyebrow: '스카이라인을 배경으로 듣는 뉴욕 재즈', summary: '무대 뒤 유리창 너머 센트럴파크와 미드타운 불빛이 겹치는 품격 있는 라이브 공연.',
    description: 'Frederick P. Rose Hall 안의 여러 공연장은 규모와 프로그램이 다르다. Dizzy’s Club은 비교적 가까운 거리에서 연주를 보고 야경도 즐길 수 있어 커플에게 특히 좋다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Lincoln_Center_during_pride_at_dusk_%2893296p%29.jpg/1920px-Lincoln_Center_during_pride_at_dusk_%2893296p%29.jpg', imageAlt: '해 질 무렵의 링컨 센터 공연예술 캠퍼스', imageCredit: 'Wikimedia Commons · Rhododendrites · CC BY-SA 4.0',
    duration: '1시간 30분–2시간 30분', budget: '$$–$$$', bestTime: '19:00 전후 첫 세트', reservation: '좌석 사전 예매 권장 · 공연장별 입장 규정 확인',
    essentials: ['Dizzy’s Club 스카이라인 뷰', '공연 30분 전 입장', '시즌 프로그램에서 아티스트 확인'],
    highlights: [{ title: '좌석', text: '무대와 야경을 모두 보려면 너무 측면보다 중앙 또는 창 쪽 시야를 좌석도에서 확인한다.' }, { title: '저녁 구성', text: '콜럼버스 서클에서 가벼운 식사를 마친 뒤 공연 하나만 잡으면 밤 일정이 과밀해지지 않는다.' }],
    transit: 'A·B·C·D·1선 59 St–Columbus Circle역, The Shops at Columbus Circle 5층.', routeTip: '센트럴파크 남서쪽 일몰 → 콜럼버스 서클 저녁 → 재즈 공연으로 마무리한다.',
    tips: ['공연 중 대화와 휴대전화 사용을 자제한다.', '클럽의 최소 주문·연령 조건을 티켓 페이지에서 확인한다.'], tags: ['재즈', '야경', '데이트'],
    coordinates: { lat: 40.7683, lng: -73.983 }, address: '10 Columbus Cir, New York, NY 10019', officialUrl: 'https://jazz.org/',
  },
  {
    id: 'met-cloisters', category: 'culture', name: '메트 클로이스터스', englishName: 'The Met Cloisters', area: '포트 트라이언 파크 · 맨해튼',
    eyebrow: '허드슨강 숲속에 옮겨온 중세 유럽', summary: '회랑 정원, 태피스트리, 석조 예배당을 천천히 걷는 맨해튼에서 가장 고요한 미술관.',
    description: '유럽 중세 건축 부재를 재구성한 메트 분관으로 포트 트라이언 파크 안에 있다. 미드타운에서 멀지만 박물관 규모가 알맞고 정원과 강 전망이 있어 도시 소음을 쉬어 가기 좋다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Cloisters%20Exterior.jpg?width=1600', imageAlt: '포트 트라이언 파크의 메트 클로이스터스', imageCredit: 'Wikimedia Commons · Ceoil / Beyond My Ken · Public Domain',
    duration: '이동 포함 3시간 30분–5시간', budget: '$$', bestTime: '개장 직후', reservation: '온라인 티켓 권장 · 보통 수요일 휴관',
    essentials: ['유니콘 태피스트리', '쿠사 회랑 정원', '포트 트라이언 허드슨강 전망'],
    highlights: [{ title: '속도', text: '방 수가 적어 작품보다 공간의 빛과 정원을 천천히 보는 편이 이곳의 장점을 살린다.' }, { title: '공원 접근', text: '190 St역 엘리베이터를 이용하면 언덕 오르막을 줄이고 공원 산책을 선택적으로 더한다.' }],
    transit: 'A선 190 St역에서 엘리베이터 출구 후 도보 약 10분, M4 버스는 입구 가까이 정차.', routeTip: '오전 클로이스터스 → 포트 트라이언 카페 휴식 → A선으로 미드타운 복귀한다.',
    tips: ['메트 본관과 같은 날 무리하게 묶지 않는다.', '정원 개방은 계절·날씨 영향을 받는다.'], tags: ['중세미술', '정원', '조용한 여행'],
    coordinates: { lat: 40.8649, lng: -73.9317 }, address: '99 Margaret Corbin Dr, New York, NY 10040', officialUrl: 'https://www.metmuseum.org/plan-your-visit/met-cloisters',
  },
  {
    id: 'tenement-museum', category: 'culture', name: '테너먼트 뮤지엄', englishName: 'Tenement Museum', area: '로어 이스트 사이드 · 맨해튼',
    eyebrow: '실제 아파트에서 듣는 이민자 뉴욕', summary: '보존된 주거 공간과 한 가족의 기록을 통해 뉴욕이 어떻게 이민자의 도시가 됐는지 듣는 투어.',
    description: '자유 관람형 박물관이 아니라 주제별 가이드 투어로만 역사적 건물에 들어간다. 음식, 노동, 가족 중 관심 주제를 하나 고르면 작은 방의 사물이 구체적인 삶으로 연결된다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tenement%20Museum.jpg?width=1600', imageAlt: '오처드 스트리트 테너먼트 뮤지엄의 역사적 건물', imageCredit: 'Wikimedia Commons · Beyond My Ken · CC BY-SA 2.0',
    duration: '1시간 30분–2시간', budget: '$$', bestTime: '오전 첫 투어', reservation: '영어 가이드 투어 사전 예약 필수에 가까움',
    essentials: ['97 Orchard St 역사 공간', '이민 가족의 구술·생활사', 'Visitor Center 서점'],
    highlights: [{ title: '투어 선택', text: '같은 건물이라도 주제가 다르다. 공식 설명의 시대와 가족 배경을 읽고 한 코스만 고른다.' }, { title: '영어 난이도', text: '설명이 중심이므로 관련 이민사 개요를 미리 읽거나 핵심 단어를 저장하면 이해가 쉬워진다.' }],
    transit: 'F선 2 Av역 또는 F·M·J·Z선 Delancey St–Essex St역에서 도보 약 5분.', routeTip: '오전 투어 → 러스 앤 도터스 또는 카츠 → 로어 이스트 사이드 거리 산책으로 잇는다.',
    tips: ['역사적 건물은 계단이 좁고 엘리베이터가 없는 투어가 있다.', '집합 장소가 방문자센터인지 티켓에서 확인한다.'], tags: ['이민사', '가이드 투어', '예약'],
    coordinates: { lat: 40.7188, lng: -73.9901 }, address: '103 Orchard St, New York, NY 10002', officialUrl: 'https://www.tenement.org/',
  },

  // SHOPPING · 8
  {
    id: 'soho', category: 'shopping', name: '소호 캐스트아이언 지구', englishName: 'SoHo Cast-Iron District', area: '소호 · 맨해튼',
    eyebrow: '건축과 플래그십을 함께 보는 쇼핑 산책', summary: '자갈길과 주철 파사드 사이에 글로벌 플래그십, 뉴욕 브랜드, 디자인 숍이 촘촘히 모인 거리.',
    description: '브로드웨이는 대형 브랜드, 프린스·스프링·머서 스트리트는 패션과 디자인 숍 중심으로 성격이 다르다. 한 건물보다 거리 전체를 편집숍처럼 즐기는 곳이다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Cast_Iron_Grand_Crosby_jeh_crop.jpg/1920px-Cast_Iron_Grand_Crosby_jeh_crop.jpg', imageAlt: '소호의 주철 건축과 거리', imageCredit: 'Wikimedia Commons · Jim.henderson · CC BY-SA 4.0',
    duration: '3–4시간', budget: '$$–$$$$', bestTime: '평일 11:00–15:00', reservation: '예약 불필요',
    essentials: ['뉴욕 한정 컬러·캡슐 제품', '독립 향수·디자인 소품', '편집숍 세일 랙'],
    highlights: [{ title: '거리 읽기', text: '브로드웨이에서 서쪽 머서·그린 스트리트까지 지그재그로 이동하면 되돌아가는 길이 적다.' }, { title: '세금', text: '뉴욕시 판매세는 8.875%다. 의류·신발은 한 품목 또는 한 켤레가 110달러 미만이면 면세될 수 있다.' }],
    transit: 'R·W선 Prince St, 6선 Spring St, A·C·E선 Canal St역 중 시작점에 맞춰 선택.', routeTip: '놀리타 브런치 → 소호 쇼핑 → 워싱턴 스퀘어 또는 트라이베카 저녁으로 잇는다.',
    tips: ['주말 오후는 보행 밀도가 높다.', '여권 원본 대신 할인에 필요한 신분증 조건을 매장별로 확인한다.'], tags: ['패션', '디자인', '거리 산책'],
    coordinates: { lat: 40.7233, lng: -74.0001 }, address: 'Prince St & Greene St, New York, NY 10012', officialUrl: 'https://www.nyc.gov/site/lpc/designations/historic-district-maps.page',
  },
  {
    id: 'macys-herald-square', category: 'shopping', name: '메이시스 헤럴드 스퀘어', englishName: "Macy's Herald Square", area: '헤럴드 스퀘어 · 맨해튼',
    eyebrow: '한 블록을 채운 미국 백화점의 원형', summary: '패션, 리빙, 미국 브랜드와 오래된 목재 에스컬레이터를 한 번에 보는 대형 백화점.',
    description: '1902년부터 이어진 플래그십으로 규모가 커서 층을 정하지 않으면 지친다. 방문자센터에서 국제 여행자 할인과 적용 제외 브랜드를 먼저 확인한다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Macy%27s_Herald_Square_August_2017_01.jpg', imageAlt: '헤럴드 스퀘어 메이시스 백화점 외관', imageCredit: 'Wikimedia Commons · Arild Vågen · CC BY-SA 4.0',
    duration: '1시간 30분–3시간', budget: '$$–$$$$', bestTime: '평일 오픈 직후', reservation: '매장 입장은 예약 불필요 · 역사 투어는 사전 확인',
    essentials: ['미국 브랜드 의류·리빙', '방문자 10% 패스 조건 확인', '역사적 목재 에스컬레이터'],
    highlights: [{ title: '효율', text: '공식 층별 안내에서 살 품목이 있는 2–3개 층만 저장하고 엘리베이터로 먼저 이동한다.' }, { title: '선물', text: 'NYC 로고 상품보다 미국 브랜드의 시즌 한정 컬러와 리빙 소품이 실용적이다.' }],
    transit: 'B·D·F·M·N·Q·R·W선 34 St–Herald Sq역과 바로 연결.', routeTip: '메이시스 → 코리아타운 점심 → 엠파이어 스테이트 빌딩 또는 킨스로 연결한다.',
    tips: ['할인 패스는 명품·화장품 등 제외 품목이 있다.', '면세점이 아니므로 영수증의 판매세를 확인한다.'], tags: ['백화점', '미국 브랜드', '실내'],
    coordinates: { lat: 40.7508895, lng: -73.9892551 }, address: '151 W 34th St, New York, NY 10001', officialUrl: 'https://www.macys.com/s/visitor-services/',
  },
  {
    id: 'moma-design-soho', category: 'shopping', name: 'MoMA 디자인 스토어 소호', englishName: 'MoMA Design Store · SoHo', area: '소호 · 맨해튼',
    eyebrow: '미술관의 시선으로 고른 생활 디자인', summary: '뉴욕 그래픽, 산업디자인, 아트 굿즈를 작품 설명과 함께 고르는 세련된 기념품 숍.',
    description: '2025년 재정비 후 다시 문을 연 소호 매장으로 미술관에 가지 않아도 컬렉션 기반 상품을 살 수 있다. 가벼운 문구와 주방 소품은 포장·운반이 쉽다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Moma%2C_2010_%2828689452400%29.jpg', imageAlt: 'MoMA의 디자인 감성을 보여 주는 미드타운 건축', imageCredit: 'Wikimedia Commons · Rodrigo Paredes · CC BY 2.0',
    duration: '45분–1시간 30분', budget: '$$–$$$', bestTime: '평일 11:00–13:00', reservation: '예약 불필요',
    essentials: ['Anthora 뉴욕 종이컵 모티프 머그', 'NYC 스카이라인 디자인', 'MoMA 한정 그래픽 소품'],
    highlights: [{ title: '선물 고르기', text: '가격대별 진열이 아니라 주제별이라 받는 사람의 생활 장면을 먼저 정하면 빠르다.' }, { title: '뉴욕 한정', text: 'MoMA·Yankees 협업처럼 도시 한정 상품은 재고가 바뀌므로 보이면 현장에서 판단한다.' }],
    transit: '6선 Spring St역에서 도보 약 4분, N·Q·R·W선 Canal St역에서 약 7분.', routeTip: '놀리타 → 디자인 스토어 → 그린·머서 스트리트 순으로 소호를 서쪽으로 횡단한다.',
    tips: ['깨지는 제품은 기내 반입 포장을 요청한다.', '미드타운 미술관점과 재고가 다르다.'], tags: ['디자인', '기념품', '소호'],
    coordinates: { lat: 40.7229153, lng: -73.9979776 }, address: '81 Spring St, New York, NY 10012', officialUrl: 'https://store.moma.org/pages/soho',
  },
  {
    id: 'strand-bookstore', category: 'shopping', name: '스트랜드 북스토어', englishName: 'Strand Book Store', area: '유니언 스퀘어 · 맨해튼',
    eyebrow: '18마일의 책으로 만든 뉴욕 서점', summary: '신간, 희귀본, 중고책과 그래픽 굿즈가 층마다 쌓인 독립 서점의 아이콘.',
    description: '1927년부터 이어진 대형 독립 서점이다. 책을 무겁게 사기보다 뉴욕 작가의 페이퍼백, 서점 로고 토트와 문구를 고르면 휴대가 쉽고 기억도 선명하다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Strand%20Bookstore%20%2848072652191%29.jpg?width=1600', imageAlt: '붉은 차양이 있는 스트랜드 북스토어', imageCredit: 'Wikimedia Commons · ajay_suresh · CC BY 2.0',
    duration: '1시간–2시간', budget: '$–$$', bestTime: '평일 오픈 직후', reservation: '예약 불필요 · 일부 희귀본실 시간 확인',
    essentials: ['18 Miles of Books 토트백', '뉴욕 작가 페이퍼백', '빈티지 프린트·엽서'],
    highlights: [{ title: '선물', text: '서점 로고 토트와 북마크는 가볍고 뉴욕 독립서점의 정체성이 분명하다.' }, { title: '탐색', text: '1층 신간, 지하 중고, 상층 아트북 중 두 구역만 정하면 오래 서서 지치는 일을 줄인다.' }],
    transit: '4·5·6·L·N·Q·R·W선 14 St–Union Sq역에서 도보 약 4분.', routeTip: '유니언 스퀘어 그린마켓 → 스트랜드 → 워싱턴 스퀘어 방향으로 남하한다.',
    tips: ['가방 검사를 요청받을 수 있다.', '무거운 아트북은 배송비와 수하물 무게를 비교한다.'], tags: ['책', '토트백', '독립상점'],
    coordinates: { lat: 40.7332796, lng: -73.9909401 }, address: '828 Broadway, New York, NY 10003', officialUrl: 'https://www.strandbooks.com/',
  },
  {
    id: 'nintendo-ny', category: 'shopping', name: '닌텐도 뉴욕', englishName: 'Nintendo New York', area: '록펠러센터 · 맨해튼',
    eyebrow: '게임 세계가 뉴욕 플래그십이 된 공간', summary: '마리오, 젤다, 동물의 숲 상품과 역사적 콘솔 전시를 함께 보는 팬들의 목적지.',
    description: '미국 내 소수의 닌텐도 직영점 중 하나로 캐릭터별 상품과 게임 체험 공간이 있다. 신작 출시나 이벤트 날에는 시간 지정 입장 또는 별도 대기 규칙이 생길 수 있다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/8/85/Nintendo_Switch_2_release_in_NYC_30.jpg', imageAlt: '록펠러센터 닌텐도 뉴욕 매장의 행사 풍경', imageCredit: 'Wikimedia Commons · SWinxy · CC BY 4.0',
    duration: '45분–1시간 30분', budget: '$–$$$', bestTime: '평일 오픈 직후', reservation: '보통 예약 불필요 · 출시·행사일 시간 지정 여부 확인',
    essentials: ['뉴욕 또는 매장 한정 상품', '마리오·젤다 봉제인형', '역대 콘솔 전시'],
    highlights: [{ title: '팬이 아니어도', text: '유리 진열장의 역사적 콘솔과 대형 캐릭터 설치물은 작은 게임 박물관처럼 볼 만하다.' }, { title: '필수템', text: '한국에서 구하기 어려운 매장 한정 핀·티셔츠를 우선 보고 부피 큰 인형은 마지막에 고른다.' }],
    transit: 'B·D·F·M선 47–50 Sts–Rockefeller Center역에서 도보 약 2분.', routeTip: 'MoMA → 닌텐도 → 록펠러센터 → 5번가 순으로 미드타운 쇼핑을 묶는다.',
    tips: ['미국 게임·충전 규격을 확인한다.', '출시일 혼잡 공지는 공식 페이지에서 확인한다.'], tags: ['게임', '캐릭터', '한정 굿즈'],
    coordinates: { lat: 40.757976, lng: -73.9794142 }, address: '10 Rockefeller Plaza, New York, NY 10020', officialUrl: 'https://www.nintendo.com/us/new-york/',
  },
  {
    id: 'tiffany-landmark', category: 'shopping', name: '티파니 랜드마크', englishName: 'The Landmark · Tiffany & Co.', area: '5번가 · 맨해튼',
    eyebrow: '주얼리 매장을 넘어선 10층짜리 뉴욕 아이콘', summary: '역사적 파사드와 현대미술, 오브제, 주얼리가 층마다 이어지는 5번가 플래그십.',
    description: '구매 계획이 없어도 쇼윈도, 계단, 예술 작품과 아카이브를 보는 문화 공간에 가깝다. 작은 실버 제품부터 하이주얼리까지 가격대가 넓다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/57th_St_5th_Av_td_%282022-04-04%29_08_-_Tiffany_%26_Co._%28727_Fifth_Avenue%29.jpg', imageAlt: '5번가 티파니 랜드마크 외관', imageCredit: 'Wikimedia Commons · Tdorante10 · CC BY-SA 4.0',
    duration: '1시간–2시간', budget: '$$$–$$$$', bestTime: '평일 10:00–12:00', reservation: '일반 매장 관람은 예약 불필요 · Blue Box Cafe 별도 예약',
    essentials: ['Return to Tiffany 소형 실버', '랜드마크 전용 오브제', '아카이브·현대미술 층'],
    highlights: [{ title: '전시와 아카이브', text: '랜드마크 전용 전시와 아카이브는 수시로 바뀌므로 방문일의 전시 일정을 확인한다.' }, { title: '카페', text: 'Blue Box Cafe는 매장 방문과 예약 체계가 다르므로 식사를 원하면 별도로 확보한다.' }],
    transit: 'N·R·W선 5 Av/59 St역에서 도보 약 3분, E·M선 5 Av/53 St역에서 약 7분.', routeTip: '센트럴파크 남동쪽 → 티파니 → 5번가 쇼윈도 → 록펠러센터로 남하한다.',
    tips: ['구매 시 한국 입국 면세 한도와 신고 규정을 확인한다.', '고가품은 호텔 보관과 보험을 고려한다.'], tags: ['주얼리', '5번가', '건축'],
    coordinates: { lat: 40.7627483, lng: -73.9738435 }, address: '727 5th Ave, New York, NY 10022', officialUrl: 'https://www.tiffany.com/stories/the-landmark/',
  },
  {
    id: 'union-square-greenmarket', category: 'shopping', name: '유니언 스퀘어 그린마켓', englishName: 'Union Square Greenmarket', area: '유니언 스퀘어 · 맨해튼',
    eyebrow: '뉴욕주 농부가 도심으로 가져온 계절', summary: '9월 사과와 토마토, 꽃, 꿀, 갓 구운 빵을 생산자에게 직접 고르는 살아 있는 로컬 시장.',
    description: '월·수·금·토에 열리는 생산자 시장으로 계절마다 품목이 달라진다. 여행자는 바로 먹을 빵과 과일, 포장된 꿀·메이플 제품처럼 운반하기 쉬운 것을 고르는 편이 좋다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Union_Square_Greenmarket.jpg', imageAlt: '유니언 스퀘어 그린마켓의 농산물 가판', imageCredit: 'Wikimedia Commons · Jjbnyc · CC BY-SA 4.0',
    duration: '45분–1시간 30분', budget: '$–$$', bestTime: '월·수·금·토 09:00–11:00', reservation: '예약 불필요 · 통상 08:00–18:00',
    essentials: ['9월 뉴욕주 사과', '로컬 꿀·메이플 제품', '빵과 제철 꽃'],
    highlights: [{ title: '먹는 기념품', text: '밀봉된 꿀이나 메이플 제품은 지역성이 분명하지만 한국 반입 규정을 먼저 확인한다.' }, { title: '현지 리듬', text: '셰프와 주민이 장 보는 오전 풍경 자체가 관광지보다 생활에 가까운 뉴욕 경험이다.' }],
    transit: '4·5·6·L·N·Q·R·W선 14 St–Union Sq역 바로 앞.', routeTip: '그린마켓 → 스트랜드 → 그래머시·플랫아이언 산책으로 동쪽과 북쪽을 잇는다.',
    tips: ['과일·식물·육가공품은 한국 검역 대상일 수 있다.', '일회용 봉투와 소액 결제 수단을 준비한다.'], tags: ['로컬 마켓', '식품', '9월 제철'],
    coordinates: { lat: 40.7368, lng: -73.9901 }, address: 'E 17th St & Union Square W, New York, NY 10003', officialUrl: 'https://www.grownyc.org/greenmarket/manhattan-union-square-m',
  },
  {
    id: 'brooklyn-flea-dumbo', category: 'shopping', name: '브루클린 플리 덤보', englishName: 'Brooklyn Flea · DUMBO', area: '덤보 · 브루클린',
    eyebrow: '다리 아래에서 찾는 빈티지 뉴욕', summary: '빈티지 의류, 레코드, 독립 제작자의 오브제를 주말 야외 시장에서 직접 고르는 경험.',
    description: '주말에 열리는 계절형 플리마켓으로 판매자가 매번 달라 목록보다 발견의 재미가 크다. 작은 프린트, 핀, 주얼리처럼 여행 가방에 안전한 물건이 좋은 기념품이다.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Vendor_display_at_Brooklyn_Flea.jpg', imageAlt: '브루클린 플리의 빈티지 물건 가판', imageCredit: 'Wikimedia Commons · Wgreaves · CC BY-SA 4.0',
    duration: '1시간–2시간', budget: '$–$$$', bestTime: '토·일 10:00–12:00', reservation: '예약 불필요 · 계절 운영·우천 공지 확인',
    essentials: ['빈티지 뉴욕 프린트', '독립 제작 주얼리·도자기', '레코드·헌책'],
    highlights: [{ title: '흥정', text: '가격표가 있어도 여러 개 구매할 때만 정중히 묻고, 카드 수수료와 현금 가격을 확인한다.' }, { title: '진품 판단', text: '고가 브랜드보다 제작자 설명을 들을 수 있는 소형 오브제와 종이 제품을 우선한다.' }],
    transit: 'F선 York St역에서 도보 약 7분, A·C선 High St역에서 약 10분.', routeTip: '브루클린 브리지 파크 → 플리마켓 → 워싱턴 스트리트 → 페리 복귀로 잇는다.',
    tips: ['주말·계절에 따라 장소가 바뀔 수 있다.', '깨지는 물건은 판매자에게 추가 포장을 요청한다.'], tags: ['빈티지', '주말시장', '브루클린'],
    coordinates: { lat: 40.7031022, lng: -73.9878619 }, address: '80 Pearl St, Brooklyn, NY 11201', officialUrl: 'https://brooklynflea.com/',
  },

  // DAY TRIPS · 8
  {
    id: 'beacon-dia', category: 'daytrip', name: '비컨과 디아 비컨', englishName: 'Beacon & Dia Beacon', area: '허드슨 밸리 · 뉴욕주',
    eyebrow: '강변 공장 안에 펼쳐진 빛과 미니멀 아트', summary: '허드슨강 열차 풍경, 거대한 현대미술, 작은 메인 스트리트를 한 날에 담는 균형 좋은 근교 여행.',
    description: '옛 나비스코 공장을 개조한 디아 비컨은 자연광과 대형 설치작품이 핵심이다. 역에서 미술관이 가깝고 무료 순환버스를 활용할 수 있어 차 없이도 가장 수월한 당일치기다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dia%20Beacon%20NY1.jpg?width=1600', imageAlt: '붉은 벽돌 공장 건물의 디아 비컨', imageCredit: 'Wikimedia Commons · Acroterion · CC BY-SA 4.0',
    duration: '뉴욕 출발 8–9시간', budget: '$$$', bestTime: 'Grand Central 09:00 전후 출발', reservation: '입장 시간권 권장 · 4–10월 통상 목–월 11:00–18:00',
    essentials: ['디아 비컨 대형 설치', '허드슨강변 열차 좌석', '비컨 메인 스트리트 카페'],
    highlights: [{ title: '차 없는 동선', text: 'Beacon역 → 디아 도보 8–10분 → 메인 스트리트 무료 루프버스 → 역 순서가 단순하다.' }, { title: '열차 자리', text: '뉴욕에서 북상할 때 진행 방향 왼쪽에 앉으면 허드슨강 풍경을 더 오래 본다.' }],
    transit: 'Grand Central에서 Metro-North Hudson Line으로 약 80–90분. 역에서 디아까지 도보 약 10분.', routeTip: '11:00 디아 → 14:00 메인 스트리트 점심·산책 → 17:00 전후 뉴욕행 열차가 여유롭다.',
    tips: ['화·수 휴관 가능성이 있어 날짜를 먼저 정한다.', '미술관 내부는 넓지만 벤치가 있어 쉬어 가며 보기 좋다.'], tags: ['현대미술', '기차 여행', '차 없이'],
    coordinates: { lat: 41.500075, lng: -73.982567 }, address: '3 Beekman St, Beacon, NY 12508', officialUrl: 'https://www.diaart.org/visit/visit-our-locations-sites/dia-beacon-beacon-united-states',
  },
  {
    id: 'cold-spring-boscobel', category: 'daytrip', name: '콜드 스프링과 보스코벨', englishName: 'Cold Spring & Boscobel House', area: '허드슨 밸리 · 뉴욕주',
    eyebrow: '앤티크 거리와 허드슨강 정원의 하루', summary: '작은 마을 산책과 강 건너 산맥 전망, 역사 저택 정원을 무리 없는 속도로 즐기는 커플 여행.',
    description: '콜드 스프링은 역과 메인 스트리트, 강변이 가까워 차 없이도 기본 산책이 가능하다. 보스코벨을 더하려면 택시나 차량을 미리 확보하고 정원·저택 투어 시간을 맞춘다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cold%20Spring%20New%20York%202025.jpg?width=1600', imageAlt: '허드슨강과 산이 보이는 콜드 스프링', imageCredit: 'Wikimedia Commons · Alex Wilcox Cheek · CC0',
    duration: '뉴욕 출발 8–9시간', budget: '$$–$$$', bestTime: '평일 오전 출발', reservation: '보스코벨 저택 투어 시간 지정권 권장 · 통상 금–월 중심 운영',
    essentials: ['메인 스트리트 앤티크 숍', '콜드 스프링 강변', '보스코벨 정원과 허드슨강 전망'],
    highlights: [{ title: '피로도 낮추기', text: '브레이크넥 리지 하이킹은 생략하고 평지인 메인 스트리트와 강변, 보스코벨 정원에 집중한다.' }, { title: '차량', text: '호출 차량이 맨해튼만큼 즉시 잡히지 않으므로 보스코벨 왕복 시간을 기사와 미리 조율한다.' }],
    transit: 'Grand Central에서 Metro-North Hudson Line 약 70–80분. 보스코벨은 역에서 차량 약 10분.', routeTip: '마을 브런치 → 보스코벨 예약 투어 → 강변 산책 → 해 지기 전 열차 순서가 좋다.',
    tips: ['앤티크 숍은 평일 휴무가 제각각이다.', '열차 귀로 시간을 캡처해 둔다.'], tags: ['작은 마을', '정원', '커플 추천'],
    coordinates: { lat: 41.419058, lng: -73.956294 }, address: 'Main St, Cold Spring, NY 10516', officialUrl: 'https://www.boscobel.org/',
  },
  {
    id: 'sleepy-hollow', category: 'daytrip', name: '태리타운과 슬리피 할로', englishName: 'Tarrytown & Sleepy Hollow', area: '웨스트체스터 · 뉴욕주',
    eyebrow: '허드슨강 저택과 미국 고딕 전설의 마을', summary: '필립스버그 매너, 오래된 묘지, 강변 마을을 기차 40분 거리에서 만나는 역사 여행.',
    description: '워싱턴 어빙의 전설과 네덜란드계 농장 역사가 겹치는 지역이다. 2026년에는 카이컷 저택이 연중 보수로 닫히므로 필립스버그 매너와 마을 산책을 중심으로 잡는다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sleepy%20Hollow%20Cemetery%20NY1.jpg?width=1600', imageAlt: '슬리피 할로 묘지의 오래된 입구와 단풍', imageCredit: 'Wikimedia Commons · Acroterion · CC BY-SA 4.0',
    duration: '뉴욕 출발 7–9시간', budget: '$$–$$$', bestTime: '금–일 오전', reservation: '필립스버그 매너 시간 지정 예약 · 카이컷은 2026년 연중 휴관',
    essentials: ['필립스버그 매너 가이드 경험', '올드 더치 처치·묘지', '태리타운 메인 스트리트'],
    highlights: [{ title: '2026년 핵심 변경', text: 'Kykuit을 일정에 넣지 않는다. 필립스버그 매너는 5월 8일–9월 27일 금–일 운영 일정을 우선 확인한다.' }, { title: '걷기', text: '태리타운역과 슬리피 할로 사이가 멀어 버스·택시를 한 번 섞으면 체력과 시간이 절약된다.' }],
    transit: 'Grand Central에서 Metro-North Hudson Line으로 Tarrytown까지 약 35–45분.', routeTip: '오전 필립스버그 매너 → 마을 점심 → 교회·묘지 → 태리타운 강변 순서로 잡는다.',
    tips: ['역사 투어는 야외 이동이 있어 비옷을 준비한다.', '묘지는 예배·장례가 있는 실제 공간이므로 조용히 방문한다.'], tags: ['미국사', '전설', '기차 여행'],
    coordinates: { lat: 41.096177, lng: -73.860235 }, address: '381 N Broadway, Sleepy Hollow, NY 10591', officialUrl: 'https://hudsonvalley.org/historic-sites/philipsburg-manor/',
  },
  {
    id: 'storm-king', category: 'daytrip', name: '스톰 킹 아트 센터', englishName: 'Storm King Art Center', area: '뉴윈저 · 허드슨 밸리',
    eyebrow: '대지와 조각 사이를 걷는 야외 미술관', summary: '약 500에이커의 구릉과 숲에 대형 조각이 놓인, 뉴욕 근교에서 가장 시각적인 하루.',
    description: '화이트 큐브 대신 들판과 하늘이 전시실이 되는 야외 조각 공원이다. 전 구역을 정복하기보다 트램과 핵심 산책 구간을 조합하면 부담 없이 풍경을 즐긴다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Storm%20King%20Museum%20Building%20Jul%2012.jpg?width=1600', imageAlt: '스톰 킹 아트 센터의 초원과 야외 조각', imageCredit: 'Wikimedia Commons · Doug Kerr · CC BY-SA 2.0',
    duration: '뉴욕 출발 8–10시간', budget: '$$$', bestTime: '개장 시간 입장', reservation: '입장·교통 사전 예약',
    essentials: ['Museum Hill 전망', 'Alexander Calder 작품군', '무료 트램 구간 이동'],
    highlights: [{ title: '추천 흐름', text: '개장 입장 → Museum Hill → 트램 이동 → 남쪽 들판 산책 → 카페 휴식 순서가 효율적이다.' }, { title: '9월', text: '한여름보다 걷기 편하고 빛이 부드럽지만 그늘이 적어 모자와 물은 여전히 필요하다.' }],
    transit: 'Port Authority 계절 직행버스를 우선 확인. 대안은 Beacon역에서 예약 차량 약 30분.', routeTip: '자연을 가장 크게 느끼는 날로 비워 두고 뉴욕 복귀 후 저녁 일정은 잡지 않는다.',
    tips: ['운영일과 셔틀은 계절별로 달라 공식 캘린더를 확인한다.', '잔디와 경사에 편한 신발을 신는다.'], tags: ['자연', '현대미술', '하루 여행'],
    coordinates: { lat: 41.4251, lng: -74.0596 }, address: '1 Museum Rd, New Windsor, NY 12553', officialUrl: 'https://stormking.org/',
  },
  {
    id: 'princeton', category: 'daytrip', name: '프린스턴', englishName: 'Princeton', area: '뉴저지',
    eyebrow: '고딕 캠퍼스와 새 미술관을 걷는 지적인 하루', summary: '아이비리그 캠퍼스, 2025년 새로 문을 연 미술관, 작은 마을 카페를 기차로 다녀온다.',
    description: '대학 캠퍼스와 Nassau Street가 붙어 있어 차 없이 이동하기 쉽다. 프린스턴대학교 미술관은 2025년 10월 새 건물로 재개관해 무료 컬렉션과 건축을 함께 볼 수 있다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nassau%20Hall%2C%20Princeton.jpg?width=1600', imageAlt: '프린스턴 대학교의 역사적인 나소 홀', imageCredit: 'Wikimedia Commons · Smallbones / Inabluemn · CC0',
    duration: '뉴욕 출발 8–9시간', budget: '$$–$$$', bestTime: '평일 08:30 전후 출발', reservation: '일반 입장은 예약 불필요 · 특별 프로그램은 별도 확인',
    essentials: ['프린스턴대학교 미술관', '채플과 나소 홀', 'Nassau Street 산책'],
    highlights: [{ title: '열차 갈아타기', text: 'Princeton Junction에서 짧은 지선 열차 Dinky로 갈아타는 시간을 포함해 앱에서 여정을 확인한다.' }, { title: '무료 미술관', text: '새 미술관은 컬렉션뿐 아니라 여러 동선을 연결하는 건축 자체가 방문 이유다.' }],
    transit: 'Penn Station에서 NJ Transit Northeast Corridor로 Princeton Junction, Dinky 환승. 약 80–100분.', routeTip: '오전 캠퍼스 건축 → 점심 → 미술관 2시간 → Nassau Street 카페 후 귀환한다.',
    tips: ['평일 통근 피크에는 열차 요금·좌석을 확인한다.', '학기 중 행사가 있으면 캠퍼스 일부 접근이 제한될 수 있다.'], tags: ['캠퍼스', '미술관', '차 없이'],
    coordinates: { lat: 40.3487, lng: -74.6593 }, address: 'Princeton University, Princeton, NJ 08544', officialUrl: 'https://artmuseum.princeton.edu/',
  },
  {
    id: 'philadelphia', category: 'daytrip', name: '필라델피아 역사 지구', englishName: 'Historic Philadelphia', area: '펜실베이니아',
    eyebrow: '미국 독립의 현장을 걷는 250주년의 도시', summary: '독립기념관, 자유의 종, 올드 시티 골목에서 미국 건국사를 하루에 압축해 본다.',
    description: '뉴욕에서 고속열차로 90분 안팎이라 당일치기가 가능하다. 2026년 미국 독립 250주년 행사로 평소보다 혼잡할 수 있어 독립기념관 예약을 중심으로 동선을 고정한다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Independence%20Hall%20Exterior%20Front.jpg?width=1600', imageAlt: '필라델피아 독립기념관의 붉은 벽돌 건물', imageCredit: 'Wikimedia Commons · Andrew Rehbein · CC BY-SA 4.0',
    duration: '뉴욕 출발 10–12시간', budget: '$$$', bestTime: '07:00대 열차', reservation: '독립기념관은 1달러 시간 지정 예약 권장 · 2026년 혼잡 예상',
    essentials: ['독립기념관 가이드 투어', '자유의 종', '리딩 터미널 마켓 또는 올드 시티'],
    highlights: [{ title: '250주년', text: '2026년은 행사와 단체 방문이 많다. 핵심 입장 시간을 먼저 확보하고 나머지를 주변에 배치한다.' }, { title: '기차 선택', text: 'Amtrak은 빠르고 편하다. 저렴한 버스는 교통 체증으로 귀로 시간이 흔들릴 수 있다.' }],
    transit: 'Moynihan Train Hall에서 Amtrak으로 30th Street Station까지 약 70–90분, 이후 지하철·택시.', routeTip: '독립기념관 첫 타임 → 올드 시티 → 점심 → 미술관 계단 또는 강변 중 하나만 더한다.',
    tips: ['뉴욕 저녁 공연과 같은 날 묶지 않는다.', '독립기념관 보안 검색 시간을 포함한다.'], tags: ['미국 역사', '고속열차', '250주년'],
    coordinates: { lat: 39.9489, lng: -75.15 }, address: '520 Chestnut St, Philadelphia, PA 19106', officialUrl: 'https://www.nps.gov/inde/planyourvisit/independencehall.htm',
  },
  {
    id: 'long-beach-ny', category: 'daytrip', name: '롱비치', englishName: 'Long Beach, New York', area: '롱아일랜드 · 뉴욕주',
    eyebrow: '지하철처럼 가볍게 떠나는 대서양 해변', summary: '맨해튼에서 한 시간 만에 모래사장과 보드워크를 만나 바다 바람을 쐬는 느린 하루.',
    description: 'LIRR 역에서 보드워크와 해변까지 걸어갈 수 있어 차가 필요 없다. 다만 2026년 공식 수영 시즌은 9월 7일까지라 출장 전후인 9월 하순에는 산책만 계획해야 한다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Long%20Beach%2C%20NY%20boardwalk%20at%20sunset.jpg?width=1600', imageAlt: '해 질 무렵 롱비치의 넓은 보드워크와 대서양 해변', imageCredit: 'Wikimedia Commons · kolikzuz · CC BY-SA 4.0',
    duration: '뉴욕 출발 6–8시간', budget: '$$', bestTime: '맑은 날 10:00–16:00', reservation: '열차 예약 불필요 · 2026년 9월 8일 이후 인명구조원 미배치·수영 금지',
    essentials: ['대서양 보드워크', '모래사장 산책', '로컬 해산물 점심'],
    highlights: [{ title: '9월 하순의 방식', text: '물놀이가 아니라 보드워크 걷기, 카페, 바다 사진을 중심으로 잡으면 안전하고 한적하다.' }, { title: '짧은 탈출', text: '열차 이동이 짧아 컨디션에 따라 반나절로 줄여도 손실이 적다.' }],
    transit: 'Penn Station 또는 Grand Central Madison에서 LIRR Long Beach Branch 약 50–65분.', routeTip: '11:00 도착 → 해변 산책 → 점심 → 카페 → 16:00 전후 귀환이 편하다.',
    tips: ['9월 8일 이후 수영하지 않는다.', '바람이 강하고 기온이 맨해튼보다 낮을 수 있으므로 얇은 방풍 재킷을 챙긴다.'], tags: ['바다', '반나절 가능', '산책'],
    coordinates: { lat: 40.583233, lng: -73.649739 }, address: 'Boardwalk, Long Beach, NY 11561', officialUrl: 'https://www.longbeachny.gov/beach',
  },
  {
    id: 'niagara-falls', category: 'daytrip', name: '나이아가라 폭포', englishName: 'Niagara Falls State Park', area: '나이아가라 폴스 · 뉴욕주',
    eyebrow: '미국 최초의 주립공원에서 마주하는 물의 규모', summary: '메이드 오브 더 미스트와 케이브 오브 더 윈즈로 폭포의 소리와 물보라를 온몸으로 느끼는 1박 여행.',
    description: '뉴욕시 근교라기보다 별도 국내여행에 가깝다. 비행기로 버펄로에 가서 1박하면 밤 조명과 다음 날 오전까지 볼 수 있고, 당일 왕복보다 지연 위험과 피로가 훨씬 낮다.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/NiagaraFallsSkylon.jpg?width=1600', imageAlt: '스카일론 타워에서 본 나이아가라 폭포 전체', imageCredit: 'Wikimedia Commons · Cimosteve · CC0',
    duration: '1박 2일 권장', budget: '$$$$', bestTime: '오후 도착·다음 날 오전 핵심 체험', reservation: '항공·숙소 사전 예약 · 보트·케이브 운영·날씨 당일 확인',
    essentials: ['Maid of the Mist 보트', 'Cave of the Winds', 'Goat Island 전망과 야간 조명'],
    highlights: [{ title: '추천 이동', text: 'LGA 또는 JFK에서 BUF까지 비행 후 차량 35–45분. 장거리 열차는 편도 약 8–9시간이라 짧은 일정에는 비효율적이다.' }, { title: '미국 측 장점', text: 'Goat Island에서 폭포 가장자리에 접근하고 케이브 오브 더 윈즈에서 물의 힘을 가까이 느낀다.' }],
    transit: '뉴욕 공항→BUF 국내선 약 1시간 30분, BUF→주립공원 차량 약 35–45분. Amtrak은 하루 이동이 길다.', routeTip: '1일차 오후 Goat Island·일몰·조명 → 2일차 오전 보트·Cave of the Winds → 버펄로 공항 복귀.',
    tips: ['휴대전화 방수팩과 갈아 신을 양말을 준비한다.', '미국·캐나다 국경을 넘을 계획이면 여권과 입국 조건을 별도로 확인한다.'], tags: ['1박 여행', '자연', '필수 예약'],
    coordinates: { lat: 43.0815, lng: -79.0648 }, address: '332 Prospect St, Niagara Falls, NY 14303', officialUrl: 'https://www.niagarafallsstatepark.com/',
  },
];
